In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import koreanize_matplotlib

In [2]:
data=pd.read_csv("./data/wine_test.csv")
data

,와인_종류,알코올_도수,사과산_함량,재_함량,재의_알칼리도,마그네슘_함량,총_페놀_함량,플라보노이드_함량,비플라보노이드_페놀_함량,프로안토시아닌_함량,색_강도,색조,희석_와인의_투과율_OD280_OD315,프롤린_함량
0,1,14.22,3.99,2.51,13.2,128,3.00,3.04,0.20,2.08,5.10,0.89,3.53,760
1,1,13.48,1.81,2.41,20.5,100,2.70,2.98,0.26,1.86,5.10,1.04,3.47,920
2,2,13.49,1.66,2.24,24.0,87,1.88,1.84,0.27,1.03,3.74,0.98,2.78,472
3,2,12.22,1.29,1.94,19.0,92,2.36,2.04,0.39,2.08,2.70,0.86,3.02,312
4,2,11.76,2.68,2.92,20.0,103,1.75,2.03,0.60,1.05,3.80,1.23,2.50,607
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
68,1,14.06,1.63,2.28,16.0,126,3.00,3.17,0.24,2.10,5.65,1.09,3.71,780
69,2,12.42,4.43,2.73,26.5,102,2.20,2.13,0.43,1.71,2.08,0.92,3.12,365
70,2,11.65,1.67,2.62,26.0,88,1.92,1.61,0.40,1.34,2.60,1.36,3.21,562
71,2,11.84,0.89,2.58,18.0,94,2.20,2.21,0.22,2.35,3.05,0.79,3.08,520

# 테스트 데이터에 트레인 데이터에 해주었던 작업을 동일하게 적용
* MinMaxScaler로 스케일링
* 홀드아웃-train, valid, test
* mms=MinMaxScaler()
* mms_train=mms.fit_transform(X_train)
* mms_valid=mms.transform(X_valid)
* mms_test=mms.transform(X_test)

In [6]:
X_test=data.drop("와인_종류", axis=1)
y_test=data['와인_종류']

# 훈련시 사용한 MinnMaxScaler 불러와 스케일링

In [7]:
import joblib

In [8]:
mms=joblib.load("./model/MinMax_info.joblib")
X_test_temp=mms.transform(X_test)
X_test=pd.DataFrame(X_test_temp, columns=X_test.columns)
X_test

,알코올_도수,사과산_함량,재_함량,재의_알칼리도,마그네슘_함량,총_페놀_함량,플라보노이드_함량,비플라보노이드_페놀_함량,프로안토시아닌_함량,색_강도,색조,희석_와인의_투과율_OD280_OD315,프롤린_함량
0,0.819527,0.629098,0.618280,0.174497,0.862069,0.703833,0.805970,0.122449,0.666667,0.364852,0.455556,0.851711,0.389652
1,0.600592,0.182377,0.564516,0.664430,0.379310,0.599303,0.788060,0.244898,0.578313,0.364852,0.622222,0.828897,0.518998
2,0.603550,0.151639,0.473118,0.899329,0.155172,0.313589,0.447761,0.265306,0.244980,0.234957,0.555556,0.566540,0.156831
3,0.227811,0.075820,0.311828,0.563758,0.241379,0.480836,0.507463,0.510204,0.666667,0.135626,0.422222,0.657795,0.027486
4,0.091716,0.360656,0.838710,0.630872,0.431034,0.268293,0.504478,0.938776,0.253012,0.240688,0.833333,0.460076,0.265966
...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,0.508876,0.342213,0.543011,0.630872,0.724138,0.233449,0.101493,0.795918,0.417671,0.765998,0.133333,0.125475,0.454325
68,0.772189,0.145492,0.494624,0.362416,0.827586,0.703833,0.844776,0.204082,0.674699,0.417383,0.677778,0.920152,0.405821
69,0.286982,0.719262,0.736559,1.067114,0.413793,0.425087,0.534328,0.591837,0.518072,0.076409,0.488889,0.695817,0.070331
70,0.059172,0.153689,0.677419,1.033557,0.172414,0.327526,0.379104,0.530612,0.369478,0.126074,0.977778,0.730038,0.229588
71,0.115385,-0.006148,0.655914,0.496644,0.275862,0.425087,0.558209,0.163265,0.775100,0.169054,0.344444,0.680608,0.195635

# train 데이터로 개발한 best 모델을 불러와 예측

In [9]:
from keras.models import load_model

2025-05-15 17:21:07.310240: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-05-15 17:21:07.339251: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1747297267.373488   74699 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1747297267.388255   74699 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1747297267.413614   74699 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1747297267.413683   74699 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1747297267.413685   74699 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1747297267.413687   74699 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-05-15 17:21:07.426411: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [10]:
y_test=pd.get_dummies(y_test)

In [ ]:
best_model=load_model("./model/wine_best_model.keras")
result=best_model.evaluate(X_test, y_test)
print("loss ", result[0], )