a. Pay Online is: 
- Customer will make an online payment through payment gateways like: [KICC](https://www.kicc.co.kr/) or [Toss](https://www.tosspayments.com/). A successful “paid online” order must have paymentId (column paymentId in table orders), and this paymentId also must be existed in table payments (when make an inner join) and orders.paymentStatus = ‘success’ and payments.status = ‘SUCCESS’ or payments.status = ‘0000’.
(To know which payment gateway is used, can check column `providerPaymentName` in table payments)

b. Pay Offline is:

- Customer will make a payment at the counter (they can pay by cash or credit card or bank transfer), but in general it means, they will not pay online via KICC or Toss.

```jsx
SELECT ***from payments p INNER JOIN orders o ON p.id = o.paymentIdWHERE p.status IN ('SUCCESS', '0000')  and o.paymentStatus != 'success'  and p.providerPaymentName != 'none';
```

In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
engine = create_engine("mysql+pymysql://dev:pwd@localhost:3306/orders")

In [4]:
import pandas as pd

excluded_ids = [
    '01H8K9XWK972V31SN3HDRGY022','01H7S6309C3ZWPVVMAWDYQDQE9',
    '01H7JEGZX7C0NCPN8ZZ3AJXASE','01H7YB33EPCWHTX1WWA9ANJCPG',
    '01H7VSQW5TB8Q4HR1Z4S5CTJKQ','01H4001EP0F1859987V7D4YJFG',
    '01H8DZZ71SYRKB4868B0WHV68E','01H98VZ8Y98MJ489TEJW7QCDS4',
    '01H7S0P3HK62VATNYDHADQPHKJ','01H9A1GTJVCTA13SA9YPEB9ETA',
    '01H7QY348FZQRVP21JAN8X4Z7R','01H7S9MDFE2FW13DPP93DV0WWP',
    '01H7SVW6ECGZ5JXPSV0YS6P7KG','01H7J0A52BKC867SHMNBZ85XTC',
    '01H847J2DGX5KEKMX386TKYGY1','01H7HNC3GKV65TAG2H3SGW7A0H',
    '01H98W8WA1X2E09TZ50DHHRJSA','01H59HRM9W7WZC0Y0Y5YK4ZJS8',
    '01H7HTY1JNFB3H0MP72X5R4QJW','01H7QXJZ7MQ63FTGJTJ5WB5TFR',
    '01H98VE7QSYH0W7AFH9Z9RY6KZ','01H3ZY9J55GM6S18YQGR3DCGQT',
    '01H8Y02HDQZTAH5AVKP51RN05G','01H847HNN73J8V4DN1V1Z7QJTT',
    '01GZZ0C5HVG9049C8AT5Y96HFS','01H9MSJKX4CCDBG2JK327BSP84',
    '01H9MAY8ZDX7KMFBS7EJYJR5AF','01HFDTAW1QRVR8P1HDKH4CNM47',
    '01HF8FYGWYH8Y27TMDPDAK2MH1','01HDJHZ6WM6QQAG627YQ549S8Z',
    '01HF3DR2VBV3D2M0SB6M32WXHQ', '01GYNFXQNDD0ATWHDFXCBHD5XG'
]
excluded_ids_str = ', '.join(f"'{cid}'" for cid in excluded_ids)

query = f"""
SELECT 
    o.createdAt,
    o.customerId,
    o.storeId,
    p.paidAmount,
    o.id AS order_id,
    o.paymentStatus AS order_status,
    p.status AS payment_status,
    p.providerPaymentName
FROM payments p
INNER JOIN orders o ON p.id = o.paymentId
WHERE
    ((
    -- 온라인 결제
        o.paymentId IS NOT NULL
        AND o.paymentStatus = 'success'
        AND p.status IN ('SUCCESS', '0000')
    )
    OR
    -- 오프라인 결제
    (
        o.paymentStatus != 'success'
        AND p.status IN ('SUCCESS', '0000')
        AND p.providerPaymentName != 'none'
    ))
    AND
    o.customerId NOT IN ({excluded_ids_str})
"""

df = pd.read_sql(query, engine)

# 결과 출력
df.head()

,createdAt,customerId,storeId,paidAmount,order_id,order_status,payment_status,providerPaymentName
0,2023-05-09 03:17:53.572400,01GZZ89SHGZJM84N36QSAMPVKB,1,29000.0,01GZZ87X94P72JDH4MCXBVQVDN,success,0000,kicc
1,2023-05-09 03:21:19.183696,01GZZ8HDKTEZHEYVQXGBVZMYPK,1,42300.0,01GZZ8E62F89YKEH23QCPV5ZHR,success,0000,kicc
2,2023-05-09 03:45:02.927580,01GZZ9TFH848XS2P1XCDKQJ38K,1,32000.0,01GZZ9SMEFX7KBC5Z3C34SYZDW,success,0000,kicc
3,2023-05-10 03:14:16.882993,01H01TEQMXDXGW2GZK2M1HGF26,1,12000.0,01H01TE0NJ98423S3Q07V54K43,success,0000,kicc
4,2023-05-10 03:41:10.071394,01H01W0CA33HV7EGVDNRKJ17VE,1,34000.0,01H01VZ81QS18JJ1RD2CK8B18H,success,0000,kicc

# 전부

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24306 entries, 0 to 24305
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   createdAt            24306 non-null  datetime64[ns]
 1   customerId           24306 non-null  object
 2   storeId              24306 non-null  int64
 3   paidAmount           24306 non-null  float64
 4   order_id             24306 non-null  object
 5   order_status         24306 non-null  object
 6   payment_status       24306 non-null  object
 7   providerPaymentName  24306 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 1.5+ MB

# testId 제외

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24306 entries, 0 to 24305
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   createdAt            24306 non-null  datetime64[ns]
 1   customerId           24306 non-null  object
 2   storeId              24306 non-null  int64
 3   paidAmount           24306 non-null  float64
 4   order_id             24306 non-null  object
 5   order_status         24306 non-null  object
 6   payment_status       24306 non-null  object
 7   providerPaymentName  24306 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 1.5+ MB

In [7]:
pd.set_option('display.max_rows', None)

In [8]:
df.groupby('customerId').count().sort_values('paidAmount', ascending=False).head(10)

,createdAt,storeId,paidAmount,order_id,order_status,payment_status,providerPaymentName
customerId,,,,,,,
01HJT1EESSP7KAK3PZ1DZT85YS,49,49,49,49,49,49,49
01J98BNWM5W38SXS3WA9DD56HQ,28,28,28,28,28,28,28
01HPQZMMFPDWB43J9910F4T71D,27,27,27,27,27,27,27
01HMD870VA0J7MH5BZDYB6MDHX,26,26,26,26,26,26,26
01JB60Y53Z8X2WGE4F24D91ECX,26,26,26,26,26,26,26
01HJ543YMHXJ29JN6RPRERREWV,25,25,25,25,25,25,25
01HJSQYASPCWZ1P0ZM9JE85AV0,22,22,22,22,22,22,22
01HJSR7BRJDJEXSYFVPFGQAVV0,21,21,21,21,21,21,21
01H9W8SZ19CAVG54Z4XGR2DWTR,21,21,21,21,21,21,21
01H8NBTC7ECMG8GNQX6F7NS657,20,20,20,20,20,20,20

In [9]:
df[df['customerId']=='01H7HNC3GKV65TAG2H3SGW7A0H']

Empty DataFrame
Columns: [createdAt, customerId, storeId, paidAmount, order_id, order_status, payment_status, providerPaymentName]
Index: []

In [10]:
df[df['customerId']=='01HJT1EESSP7KAK3PZ1DZT85YS']

,createdAt,customerId,storeId,paidAmount,order_id,order_status,payment_status,providerPaymentName
3562,2023-12-29 05:40:31.260502,01HJT1EESSP7KAK3PZ1DZT85YS,3,8500.0,01HJT1D8CWZCFZW1TVFWE3DPMC,success,SUCCESS,kicc
4067,2024-01-20 05:43:49.563627,01HJT1EESSP7KAK3PZ1DZT85YS,3,9900.0,01HMJPB41V83YCEE1YXW42FPAH,success,SUCCESS,kicc
4320,2024-01-30 05:08:01.954596,01HJT1EESSP7KAK3PZ1DZT85YS,3,9900.0,01HNCC8RS2T90DTC9GKSA0BA0H,success,SUCCESS,kicc
4343,2024-01-31 05:40:26.676523,01HJT1EESSP7KAK3PZ1DZT85YS,3,9900.0,01HNF0GTXM2KWEC2JCR649GHZD,success,SUCCESS,kicc
4456,2024-02-05 06:09:30.234932,01HJT1EESSP7KAK3PZ1DZT85YS,3,9900.0,01HNVY5MKTG1AAD1TTDB9BP4BZ,success,SUCCESS,kicc
4473,2024-02-06 05:59:41.804087,01HJT1EESSP7KAK3PZ1DZT85YS,3,9900.0,01HNYG0CZC1VZ1PNQ8AYTTNT53,success,SUCCESS,kicc
4776,2024-02-17 07:15:47.849566,01HJT1EESSP7KAK3PZ1DZT85YS,3,8500.0,01HPTYQN095CCC7FD8SKWXWG73,success,SUCCESS,kicc
5018,2024-02-26 05:39:29.845321,01HJT1EESSP7KAK3PZ1DZT85YS,3,8000.0,01HQHYSSDNM255E20EXJSMQ944,success,SUCCESS,kicc
5119,2024-03-02 06:08:48.443703,01HJT1EESSP7KAK3PZ1DZT85YS,3,9500.0,01HQYWF1SVDJCDSVSW5TQY13TP,success,SUCCESS,kicc
5370,2024-03-13 07:19:29.760202,01HJT1EESSP7KAK3PZ1DZT85YS,3,9500.0,01HRVAWCQ0RGJ0RAMMZT707JR2,success,SUCCESS,kicc
5532,2024-03-22 01:29:49.047404,01HJT1EESSP7KAK3PZ1DZT85YS,3,7500.0,01HSHWEJQQDCBV0BDWTXD1F1ZJ,success,SUCCESS,kicc
5673,2024-03-26 06:07:55.913462,01HJT1EESSP7KAK3PZ1DZT85YS,3,9900.0,01HSWNYPG9DYSYE8ZRT11M1XAT,success,SUCCESS,kicc
5695,2024-03-28 01:42:30.143353,01HJT1EESSP7KAK3PZ1DZT85YS,3,19000.0,01HT1BJ3ZZ46XGG3Y6A7VTRXHZ,success,SUCCESS,kicc
5994,2024-04-09 07:06:58.765724,01HJT1EESSP7KAK3PZ1DZT85YS,3,9900.0,01HV0TWWADH0WMAQ7V4J5W14TY,success,SUCCESS,kicc
6199,2024-04-18 10:10:42.266051,01HJT1EESSP7KAK3PZ1DZT85YS,3,9900.0,01HVRAZRETS8WNZ4XVFQT7WJWE,success,SUCCESS,kicc
6204,2024-04-19 06:09:31.404517,01HJT1EESSP7KAK3PZ1DZT85YS,3,8900.0,01HVTFJVRCCJ411C5XWDY9FG26,success,SUCCESS,kicc
6267,2024-04-22 05:10:04.553722,01HJT1EESSP7KAK3PZ1DZT85YS,3,9500.0,01HW23C5G9KA5FYJX2CCZFARK4,success,SUCCESS,kicc
6315,2024-04-24 06:11:19.938220,01HJT1EESSP7KAK3PZ1DZT85YS,3,8900.0,01HW7BNRR2A3MCXET0QVCQHQZS,success,SUCCESS,kicc
6448,2024-04-30 07:16:17.439229,01HJT1EESSP7KAK3PZ1DZT85YS,3,8500.0,01HWPXS0WZNDZXXTX6E9Q4Y34S,success,SUCCESS,kicc
6469,2024-05-01 07:12:02.305194,01HJT1EESSP7KAK3PZ1DZT85YS,3,8900.0,01HWSFXYR1XDEKNXHQ69SXBA2C,success,SUCCESS,kicc
7490,2024-07-03 06:14:33.274978,01HJT1EESSP7KAK3PZ1DZT85YS,3,8550.0,01J1VKNZHTWYJXQ9SNM0H1ZMXK,success,SUCCESS,kicc
7592,2024-07-09 08:16:40.330969,01HJT1EESSP7KAK3PZ1DZT85YS,3,8900.0,01J2B91WWAF7DWAD1Q0K5SH9DW,success,SUCCESS,kicc
7634,2024-07-12 07:07:19.989652,01HJT1EESSP7KAK3PZ1DZT85YS,3,9900.0,01J2JW931NDWE17TE9EAAPYX6G,success,SUCCESS,kicc
7694,2024-07-16 08:08:40.900038,01HJT1EESSP7KAK3PZ1DZT85YS,3,8900.0,01J2X9C9P4Z8R2RMW33AX8FREB,success,SUCCESS,kicc
7713,2024-07-18 08:07:46.743550,01HJT1EESSP7KAK3PZ1DZT85YS,3,9900.0,01J32E42SQ5KC5DM4H2NCX13AP,success,SUCCESS,kicc
7730,2024-07-20 08:10:33.943113,01HJT1EESSP7KAK3PZ1DZT85YS,3,9900.0,01J37K2M2QK89MWK1MK82SN7VV,success,SUCCESS,kicc
7754,2024-07-22 06:12:15.471529,01HJT1EESSP7KAK3PZ1DZT85YS,3,8900.0,01J3CH3DZFFD4D1GTEPNM5TYXB,success,SUCCESS,kicc
7804,2024-07-25 05:57:28.043664,01HJT1EESSP7KAK3PZ1DZT85YS,3,9900.0,01J3M7EGBB324E07Y2BN77R8FX,success,SUCCESS,kicc
7859,2024-07-30 06:37:48.794585,01HJT1EESSP7KAK3PZ1DZT85YS,3,9900.0,01J415QZBT1T8W714M72YCQFT6,success,SUCCESS,kicc
7890,2024-08-01 06:46:13.532436,01HJT1EESSP7KAK3PZ1DZT85YS,3,9900.0,01J46B0T8W6GQT8Y98G9YQMJ0M,success,SUCCESS,kicc
7996,2024-08-10 06:44:50.399653,01HJT1EESSP7KAK3PZ1DZT85YS,3,9500.0,01J4XGGR2ZSTMZ3THWMQZTSBAB,success,SUCCESS,kicc
8108,2024-08-20 05:11:30.132152,01HJT1EESSP7KAK3PZ1DZT85YS,3,9900.0,01J5Q3512MG1YVD7RT2M7NGY34,success,SUCCESS,kicc
8210,2024-08-27 01:38:34.526598,01HJT1EESSP7KAK3PZ1DZT85YS,3,8910.0,01J68QR5WYCHDAZ3ZFYZETEY8D,success,SUCCESS,kicc
8250,2024-08-30 08:10:48.644426,01HJT1EESSP7KAK3PZ1DZT85YS,3,8910.0,01J6H5CHE4YW3C4CE8N98MX9GG,success,SUCCESS,kicc
8538,2024-09-12 06:39:38.676491,01HJT1EESSP7KAK3PZ1DZT85YS,3,9900.0,01J7JFAYNMQ9CCR6HG5CHQT1AN,success,SUCCESS,kicc
8698,2024-09-20 05:55:05.874428,01HJT1EESSP7KAK3PZ1DZT85YS,3,7500.0,01J86ZZ4GJVTK7QR1S289G6PQB,success,SUCCESS,kicc
8819,2024-09-24 10:06:26.408327,01HJT1EESSP7KAK3PZ1DZT85YS,3,9900.0,01J8HQY7K84K4GXTJXW0G46G4F,success,SUCCESS,kicc
9289,2024-10-12 07:30:31.505286,01HJT1EESSP7KAK3PZ1DZT85YS,3,9900.0,01J9ZT5NYHMJM9NDJ9W5B4HDW2,success,SUCCESS,kicc
9459,2024-10-17 07:08:23.990382,01HJT1EESSP7KAK3PZ1DZT85YS,3,9900.0,01JACMWRHPZNQFTV103D5J1JQ7,success,SUCCESS,kicc
10210,2024-10-28 09:06:21.202199,01HJT1EESSP7KAK3PZ1DZT85YS,3,9900.0,01JB960MWJSYNWBZFXG67CB9R5,success,SUCCESS,kicc
10951,2024-11-04 09:38:02.191370,01HJT1EESSP7KAK3PZ1DZT85YS,3,9900.0,01JBV8KPAFA05A679C6ZC5CBKH,success,SUCCESS,kicc
11719,2024-11-23 10:08:00.358039,01HJT1EESSP7KAK3PZ1DZT85YS,3,9900.0,01JDC7W7B1TZ9TK83CVGPGR02T,success,SUCCESS,kicc
11774,2024-11-25 07:37:54.533249,01HJT1EESSP7KAK3PZ1DZT85YS,3,9900.0,01JDH42TK3HGXJ9JMD9AAKD1TS,success,SUCCESS,kicc
13124,2024-12-07 09:14:21.378191,01HJT1EESSP7KAK3PZ1DZT85YS,3,9900.0,01JEG6C1SX4DFCPH57HEST6YH9,success,SUCCESS,kicc
13470,2024-12-18 09:09:15.986884,01HJT1EESSP7KAK3PZ1DZT85YS,3,9500.0,01JFCGEMJHRQRX81YBSSATZZXH,success,SUCCESS,kicc
13804,2024-12-31 09:10:13.591650,01HJT1EESSP7KAK3PZ1DZT85YS,3,8500.0,01JGDZNQTN6YTJ8HKFPKZ23YYF,success,SUCCESS,kicc
14364,2025-01-04 08:45:40.959689,01HJT1EESSP7KAK3PZ1DZT85YS,3,9900.0,01JGR7VNPXEAB9XRFGN0F759YY,success,SUCCESS,kicc
17156,2025-02-11 06:08:02.421089,01HJT1EESSP7KAK3PZ1DZT85YS,3,8000.0,01JKSSYAVHHPKXM590FQ2Y9CR1,success,SUCCESS,kicc
17756,2025-02-15 06:05:38.463367,01HJT1EESSP7KAK3PZ1DZT85YS,3,9900.0,01JM43CT8WSSZWKNAN2KN9PYZH,success,SUCCESS,kicc