# pandas

In [1]:
# pip install pandas
# conda install pandas

* numpy를 내부적으로 활용함
* 데이터 분석에 특화된 데이터 구조 제공(테이블, dataframe)
* 다양한 데이터 분석 함수 제공
* 데이터베이스에 쉽게 연결 가능
* json 데이터 html의 table 요소를 dataframe으로 손쉽게 변형 가능

# pandas에서 다루는 데이터 타입 2가지
## 1) DataFrame: 2차원 표형식 데이터
* python의 dict와도 비슷. 하나의 key에 list 형태의 value가 매칭되어 있는 형태
* {key1: [value1, value2, value3], key2: [value1, value2, value3]}

## 2) Series: 1차원의 벡터형식 데이터
* python의 list, tuple, ndarray의 1차원 상태와 비슷

In [2]:
import pandas as pd

# 데이터프레임 만들기
pd.DataFrame{key1: [value1, value2], key2: [value1, value2]}

In [3]:
df= pd. DataFrame(
{'이름':['홍길동','둘리','또치','도우너'],
'주소':['서울','의정부','고양','성남'],
'취미': ['음악감상','놀기', '달리기','바이올린']})

In [4]:
df

    이름   주소    취미
0  홍길동   서울  음악감상
1   둘리  의정부    놀기
2   또치   고양   달리기
3  도우너   성남  바이올린

In [5]:
df['이름'][0]

'홍길동'

# Series 만들기
* pd.Series([리스트나 튜플], name="컬럼명")
* 이름을 가지고 있는 list/벡터
* dataframe에서 컬럼 1개를 잘라온 형태

In [6]:
ages=pd.Series([22,53,35], name="나이")
ages

0    22
1    53
2    35
Name: 나이, dtype: int64

In [7]:
ages.dtype

dtype('int64')

In [8]:
ages[0]

22

In [9]:
ages[0:2]

0    22
1    53
Name: 나이, dtype: int64

In [10]:
ages[::-1]

2    35
1    53
0    22
Name: 나이, dtype: int64

In [11]:
ages.min

<bound method Series.min of 0    22
1    53
2    35
Name: 나이, dtype: int64>

In [12]:
ages.max()

53

In [13]:
ages.sum()

110

In [14]:
ages.cumsum()

0     22
1     75
2    110
Name: 나이, dtype: int64

In [15]:
ages.mean()

36.666666666666664

In [16]:
ages.median()

35.0

# 판다스에서 자료 불러오기, 저장하기
* csv, excel, tsv(탭 8개에 한 줄), html, sql
* pd.read_확장자명(파일경로, 옵션)

excel 파일 불러오기

In [17]:
pip install openpyxl

Requirement already satisfied: openpyxl in /home/fintech/miniforge3/envs/fintech/lib/python3.9/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /home/fintech/miniforge3/envs/fintech/lib/python3.9/site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [18]:
df_excel= pd.read_excel('./data/Online Retail.xlsx')
df_excel

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [19]:
df_excel2=pd.read_excel("./data/아파트(매매)_실거래가_20240806113828.xlsx", header=12, usecols=[1,2,3,4,5])
df_excel2

/home/fintech/miniforge3/envs/fintech/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

                       시군구      번지    본번  부번                단지명
0         서울특별시 영등포구 당산동5가      42    42   0          당산삼성래미안4차
1      강원특별자치도 원주시 지정면 가곡리    1512  1512   0  원주롯데캐슬골드파크1차(5단지)
2        대구광역시 달성군 화원읍 구라리    1650  1650   0             대곡역래미안
3             광주광역시 남구 진월동   312-7   312   7                 광명
4             광주광역시 남구 진월동  331-93   331  93                 중흥
...                    ...     ...   ...  ..                ...
37575        서울특별시 송파구 장지동     849   849   0          송파파인타운3단지
37576        부산광역시 사상구 모라동     552   552   0               백양그린
37577        광주광역시 광산구 비아동   152-5   152   5                 호반
37578        부산광역시 사상구 모라동     552   552   0               백양그린
37579         대구광역시 북구 읍내동  1366-2  1366   2               칠곡보성

[37580 rows x 5 columns]

In [20]:
import pandas as pd
df_csv = pd.read_csv("./data/아파트(매매)_실거래가_20240806113828.csv", header=12)
df_csv

,NO,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),...,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형
0,1,서울특별시 영등포구 당산동5가,42,42,0,당산삼성래미안4차,115.7800,202407,31,"139,000",...,4,개인,개인,2003,당산로 214,-,직거래,-,-,아파트
1,2,강원특별자치도 원주시 지정면 가곡리,1512,1512,0,원주롯데캐슬골드파크1차(5단지),84.9644,202407,31,"38,900",...,10,개인,개인,2019,신지정로 250,20240802,중개거래,강원 원주시,-,아파트
2,3,대구광역시 달성군 화원읍 구라리,1650,1650,0,대곡역래미안,84.5958,202407,31,"29,500",...,11,개인,개인,2007,비슬로539길 35,-,중개거래,대구 달성군,-,아파트
3,4,광주광역시 남구 진월동,312-7,312,7,광명,70.6250,202407,31,"16,900",...,1,개인,개인,1998,광복마을길 63,-,중개거래,광주 남구,-,아파트
4,5,광주광역시 남구 진월동,331-93,331,93,중흥,84.8400,202407,31,"17,500",...,13,개인,개인,1992,서문대로749번마길 30,-,직거래,-,24.07.31,아파트
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37575,37576,서울특별시 송파구 장지동,849,849,0,송파파인타운3단지,84.9800,202407,1,"117,500",...,14,개인,개인,2008,충민로 152,-,중개거래,서울 송파구,-,아파트
37576,37577,부산광역시 사상구 모라동,552,552,0,백양그린,41.3000,202407,1,"7,000",...,8,개인,개인,1992,모라로110번길 88,-,중개거래,부산 사상구,24.07.10,아파트
37577,37578,광주광역시 광산구 비아동,152-5,152,5,호반,59.8800,202407,1,"15,400",...,5,개인,개인,1998,비아로 185,-,중개거래,광주 광산구,24.07.26,아파트
37578,37579,부산광역시 사상구 모라동,552,552,0,백양그린,41.3000,202407,1,"7,500",...,10,개인,개인,1992,모라로110번길 88,-,중개거래,부산 사상구,24.07.19,아파트
37579,37580,대구광역시 북구 읍내동,1366-2,1366,2,칠곡보성,84.9800,202407,1,"21,000",...,9,개인,개인,1992,구암로21길 26,-,중개거래,대구 북구,-,아파트

In [21]:
df_json=pd.read_json("./data/서울특별시_관광지입장정보_2011_2016.json")
df_json

    ForNum  NatNum  addrCd gungu      resNm  rnum   sido  yyyymm
0    44722   75991    1111   종로구        창덕궁     1  서울특별시  201112
1        0   11017    1111   종로구        운현궁     2  서울특별시  201112
2   132399  237330    1111   종로구        경복궁     3  서울특별시  201112
3     3133   21267    1111   종로구        창경궁     4  서울특별시  201112
4    18226   24223    1111   종로구         종묘     5  서울특별시  201112
..     ...     ...     ...   ...        ...   ...    ...     ...
62    5588   44232    1141  서대문구  서대문형무소역사관     8  서울특별시  201512
63       0   22587    1141  서대문구  서대문자연사박물관     9  서울특별시  201512
64   29520    8822    1144   마포구    트릭아이미술관    10  서울특별시  201512
65       3    1647    1165   서초구      헌릉ㆍ인릉    11  서울특별시  201512
66     492   14454    1168   강남구      선릉·정릉    12  서울특별시  201512

[67 rows x 8 columns]

In [22]:
# html은 리스트 형태. df_html[0] 해야지 표를 볼 수 있음
df_html=pd.read_html("./data/corpList.htm")
df_html[0]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,한국제15호스팩,금융 지원 서비스업,기업인수합병,2024-06-26,12월,유한,NaN,서울특별시
1,에스오에스랩,"측정, 시험, 항해, 제어 및 기타 정밀기기 제조업; 광학기기 제외",산업용 및 차량용 라이다(LiDAR),2024-06-25,12월,정지성,홈페이지 보기,광주광역시
2,미래에셋비전스팩6호,금융 지원 서비스업,기업인수합병,2024-06-24,12월,정명훈,NaN,서울특별시
3,에이치엠씨제7호스팩,금융 지원 서비스업,기타금융,2024-06-24,12월,강신명,NaN,서울특별시
4,파라다이스,유원지 및 기타 오락관련 서비스업,"카지노, 호텔, 복합리조트",2024-06-24,12월,최종환..,홈페이지 보기,서울특별시
5,한중엔시에스,"전동기, 발전기 및 전기 변환 · 공급 · 제어 장치 제조업","수냉식 냉각시스템 ESS Parts, 공랭식 ESS Module Parts, EV ...",2024-06-24,12월,김환식,홈페이지 보기,경상북도
6,KB제29호스팩,금융 지원 서비스업,기업인수합병,2024-06-21,12월,서영화,NaN,서울특별시
7,미래에셋비전스팩5호,금융 지원 서비스업,기업인수합병,2024-06-19,12월,김대호,NaN,서울특별시
8,씨어스테크놀로지,의료용 기기 제조업,심전도검사솔루션 입원환자모니터링솔루션,2024-06-19,12월,이영신,홈페이지 보기,경기도
9,한국제14호스팩,금융 지원 서비스업,기업인수합병,2024-06-19,12월,변성환,NaN,서울특별시
10,디비금융스팩12호,기타 금융업,기업인수 및 합병,2024-06-18,12월,김창희,NaN,서울특별시
11,라메디텍,의료용 기기 제조업,초소형 레이저 의료기기 및 미용기기,2024-06-17,12월,최종석,NaN,서울특별시
12,그리드위즈,"그외 기타 전문, 과학 및 기술 서비스업","수요관리 서비스, 전기차 충전기 모뎀 등",2024-06-14,12월,김구환,홈페이지 보기,경기도
13,다원넥스뷰,사진장비 및 광학기기 제조업,LSMB(Laser Micro Bonding System),2024-06-11,12월,남기중,홈페이지 보기,경기도
14,미래에셋비전스팩4호,금융 지원 서비스업,기업인수목적회사(기타금융서비스),2024-05-29,12월,김정수,NaN,서울특별시

In [23]:
from sqlalchemy import create_engine
import pymysql
import pandas as pd
pymysql.install_as_MySQLdb()

In [24]:
engine=create_engine("mysql+pymysql://root:1234@localhost:3306/exchange_rate")
conn=engine.connect()
df_sql=pd.read_sql("exchange_rate", con=conn)
df_sql

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

# 타이타닉 데이터셋으로 pandas 기능 익히기

In [ ]:
df=pd.read_csv("./data/Titanic_train.csv")
df

* 데이터의 일부만 보기
* 앞쪽 head(행개수), 뒷쪽 tail(행개수)
* 기본 값은 5행

In [ ]:
df.head()

In [ ]:
df.tail(1)

In [ ]:
# 데이터 프레임 각 컬럼의 데이터타입
df.dtypes

# .info
* 컬럼명, null이 아닌 데이터 개수, 데이터타입을 출력

In [ ]:
df.info()

# .describe()
* 데이터프레임의 숫자 데이터의 기초통계를 보여주는 함수
* count, mean, std, min, 25%, 50%, 75%, max

# 판다스 데이터 프레임에서 일부 자료만 추출하기

* 데이터프레임에서 1개 컬럼만 가져오기

In [ ]:
df.head(1)

In [ ]:
df['Name']

In [ ]:
print(type(df['Name']))

* 2개 이상의 컬럼을 가져오기

In [ ]:
df[['Name','Age']]

In [ ]:
df[['Age','Name','Pclass']]

* 데이터프레임의 컬럼 순서 바꾸기

In [ ]:
df.columns

In [ ]:
df[['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']]

# 데이터프레임에서 일부 컬럼만 가져오기2
* loc: 인덱스 이름과 컬럼명으로 데이터 일부를 추출해 가져옴
    * df.loc[시작인덱스: 끝인덱스, ['컬럼명1','컬럼명2']
* iloc: 인덱스를 이용해 슬라이싱으로 데이터의 일부를 가져옴
    * df.iloc[시작 row인덱스: 끝 row 인덱스,  시작 column index: 끝 column index]

## loc

In [ ]:
df.loc[100:130, ['Name','Age']]

In [ ]:
df.loc[101,['Age']]

In [ ]:
df.loc[101,['Age']]=29

In [ ]:
df.loc[100:110,['Age']]

In [ ]:
display(df.loc)

* 특정 컬럼에서 유일값(중복되지 않은 고유한 값) 출력하기
* .unique()

In [ ]:
df['Embarked'].unique()

In [ ]:
df['Embarked'].nunique

In [ ]:
df['Embarked'].value_counts()

In [ ]:
# ascending 옵션은 value의 개수에 따라서 오름차순, 내림차순 정렬
df['Pclass'].value_counts(ascending=False)

In [ ]:
df['Age'].value_counts(sort=False)

In [ ]:
df['Pclass'].value_counts(ascending=True)

* 데이터를 정렬하는 함수
* sort_values(by="컬럼명")
* order by

In [ ]:
df.sort_values(by='Age', ascending=False)

* 기준컬럼 2개로 정렬할 때

In [ ]:
df.sort_values(by=['Pclass', 'Age'], ascending=False)

* 컬럼을 인덱스로 지정하기
* set_index("컬럼명")

In [ ]:
df.set_index(["PassengerId","Name"])

In [ ]:
df.iloc[889:, [1,3]]

In [ ]:
df.loc[(889,'Johnston, Miss. Catherine Helen "Carrie"'): (891, 'Dooley, Mr. Patrick'),['Pclass','Age']]

* 인덱스를 숫자로 초기화
* reset_index(drop=True)

# 데이터프레임에서 일부 칼럼만 가져오기2
* loc: 인덱스 이름과 컬럼명으로 데이터의 일부를 추출해 가져옴
    * df.loc[시작_row_인덱스: 끝_row_인덱스,['컬럼명1','컬럼명2']
* iloc: 인덱스를 이용해 슬라이싱으로 데이터의 일부를 가져옴
    * df.iloc[시작 row index: 끝_row_index, 시작_column_index: 끝_column_index]

* loc[시작_row_인덱스: 끝_row_인덱스

In [ ]:
df.loc[100:130, ['Name','Age']]

In [ ]:
df.loc[109, ['Age']]

In [ ]:
df.loc[101, ['Name','Age']]
print(type(df.loc[101,['Name','Age']]))

In [ ]:
display(df.loc[101:102,['Name','Age']])

In [ ]:
df.iloc[0:10, 0:13]

In [ ]:
df.iloc[4: , -5: ]

In [ ]:
df.iloc[:10:-1, ::-1]

In [ ]:
df.loc[100:130, ['Name','Age']]

In [ ]:
df.loc[109:130, ['이름','나이']]

In [ ]:
df.loc[109,['나이']]

In [ ]:
df.loc[109,['나이']]=29
df.loc[109,['나이']]

In [ ]:
df.describe()

In [ ]:
static=df.describe()
print(type(static))

In [ ]:
static.loc['min':'max',['나이','티켓가격']]

In [ ]:
static.loc['75%']+((static.loc['75%']-static.loc['25%']*1.5))

In [ ]:
df.iloc[4:11, -5:]

In [ ]:
df.iloc[4,4]

In [ ]:
df.iloc[:10:-1, ::-1]

In [ ]:
df.iloc[:10:3, ::3]

In [ ]:
df.columns

In [ ]:
df['목적지'].nunique

* 데이터를 정렬하는 함수

In [ ]:
df=df.set_index(["PassengerId","Name"])

In [ ]:
df.index

In [ ]:
# df.reset_index(drop=True)
df=df.reset_index()
df

In [ ]:
df.columns

In [ ]:
df.rename(columns={'PassengerId': 'Pid', 'Survived':'surv'}, inplace=True)

* 컬럼 삭제하기
* del df['컬럼명']
* df.

In [ ]:
df.pop('부모자식수')
df

In [ ]:
df=df.drop('가족수', axis=1)

In [ ]:
drop_cols=['승객번호','이름','티켓번호']

In [ ]:
df.drop(drop_cols)

* 데이터 타입 바꾸기
* astype(자료형)
* apply

In [ ]:
df.info()

In [ ]:
df['나이']=df['나이'].astype('float')
df['나이']=df['티켓가격'].astype('float16')
df['승객번호']=df['승객번호'].astype('int8')
df.info()

In [ ]:
df['티켓가격']=df['티켓가격'].apply(float)

In [ ]:
df.info()

In [ ]:
df['승객번호']=df['승객번호'].apply(lambda x: "짝수" if float(x)%2==0)

# 판다스 데이터프레임에서 조건에 맞는 행만 가져오기
* df[df['컬럼명']조건식]
* 조건식 연산자 <, <=, >, >=, ==, !=, &, I]

In [ ]:
df[df['승객번호']==3]

In [ ]:
df[df['나이']]

In [ ]:
df[(df['성별']=='female')]

In [ ]:
df[(df['성별']=='male')&(df['선실등급']=="1")]

In [ ]:
df=df.rename(columns={'이름':'선실등급','선실등급':'이름'})

In [ ]:
df[df['선실등급']==1, '티켓가격']

In [ ]:
df[df['이름']=='Joseph']

In [ ]:
df[df['이름'].str.contains("Joseph")]

* 승객이름에서 ()없애기
* 반복문/리스트표현식을 이용해 없애기

In [ ]:
result=[]
for name in df['이름']:
    result.append(name.replace())

In [ ]:
%%time
df['Name'].apply(lambda name: name.replace("(", ""))

In [ ]:
%%time
df['이름'].str.replace("(","").str.replace(")","")

In [ ]:
df['이름']=df['이름'].str.split(",")

In [ ]:
# " ".join(list)
df['Name']=df['Name'].str.join(" ")

In [ ]:
df['이름']

In [ ]:
df['Name']=df['이름'].str.split(",")

In [ ]:
df['first_name']=df['이름'].apply(lambda x, x[0])
df['second_name']=df['이름'].apply(lambda x: x[1])

# groupby
* 특정 기준 컬럼 지정해서 다른 컬럼의 통계량(평균, 최소, 최대)
* df[['보고싶은 컬럼1', '보고싶은컬럼2']].groupby('기준컬럼').집합함수(mean, max)

In [ ]:
survbysex=df[['성별','생존여부']].groupby(['성별']).value_counts

In [ ]:
df3.loc[[('female',0),('male',0)],'count']

In [ ]:
df[['성별','생존여부']].groupby(['성별']).mean()

In [ ]:
df.columns

In [ ]:
df[['Pclass','Survived']].groupby('Pclass')

In [ ]:
df[['선실등급','생존여부']].groupby('선실등급').mean()

In [ ]:
df['성별','선실등급','생존여부'].

In [ ]:
df['성별','나이'].groupby('성별').mean()

In [ ]:
df[['Sex','Age']].groupby('성별').

In [ ]:
df.isna().sum()/len(df) * 100

In [ ]:
df.isna().sum()/ len(df) * 100

dropna() 결측값이 있는 행을 삭제

df.dropna()

In [ ]:
round(df['Age'].mean())

In [ ]:
import numpy as np

In [ ]:
# NaN: Not a Number, Nan의 데이터타입 = float
nan_index=df[df['나이'].isna()==True].index

In [ ]:
df.loc

# 여러개의 데이터프레임 합치기
* concat: 두 개의 데이터 프레임을 1개로 합침
* merge: sql join과 같은 역할 공통된 기준 컬럼 매칭해서 합침
* join: sql join과 같은 역할 index가 같은 것끼리 합침

In [ ]:
passenger = pd.read_sql("p_info")

In [ ]:
print("passenger",passenger.shape)
print("ticket", ticket.shape)
print("survived", survived.shape)

In [ ]:
df1=pd.concat([passenger, ticket, survived], axis=1)
joined_df=pd.merge(passenger, ticket, how="inner",on="PassengerId")

In [ ]:
passenger2=passenger.copy()
passenger2.rename(columns={"PassengerId":"pid"})

In [ ]:
passenger2.columns

In [ ]:
ticket.columns

In [ ]:
pd.merge(passenger2, ticket, how='inner', on=)

In [ ]:
passenger=passenger.set_index("PassengerId")

In [ ]:
passengerId

In [ ]:
ticket=ticket.set_index("PassengerId")

# 인덱스가 섞여 있는 데이터를 불러와서 join 하기

In [ ]:
engine= create_engine("mysql+pymysql://user:password@localhost:3306/exchange_rate")
conn=engine.connect()
passenger3 = pd.read_sql("passenger", con=conn)
ticket3=pd.read_sql("ticket", con=conn)
surv3=pd.read_sql("surv", con=conn)

In [ ]:
print(len(passenger3))
print(len(ticket3))

In [ ]:
# merge의 기본 조인법: inner
pd.merge(passenger3, ticket3, on="PassengerId")

In [ ]:
passenger3.join(ticket3, on="PassengerId")

In [ ]:
passenger4=passenger3.set_index("PassengerId")
ticket3=ticket3.set_index("Passengerid")

In [ ]:
# join은 기본값이 left join
passenger.join(ticket, how='inner')

In [ ]:
toss[toss['사용자']]

In [ ]:
toss.duplicated().sum()

In [ ]:
toss=toss.drop_duplicates()
toss

In [ ]:
toss.loc[400:500]

In [ ]:
data.drop("Cabin", axis=1, inplace=True)

In [ ]:
data['Embarked']=data['Embarkd']

In [ ]:
from sqlalchmey import create_engine
import pymysql 
pymysql.install_as_MYSQLdb()

In [ ]:
engine=create_engine("mysql+pymysql://root:1234@localhost:3306/exchange_rate")
conn=engine.connect()
df_sql=pd.read_sql
conn.close()
df_sql

In [ ]:
conn=engine.connect()
passenger=pd.read_sql("p_info", con=conn)
conn.close()
passenger

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("./data/Titanic_train.csv")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
df.loc[0:3, ['PassengerId','Pclass']]

In [ ]:
df.iloc[0:3, 0:3]

In [ ]:
static=df.describe()

In [ ]:
static

In [ ]:
static.loc['min':'max',['PassengerId','Age']]

In [ ]:
static.loc['75%']+((static.loc['75%']-static.loc['25%']*1.5))

In [ ]:
df.iloc[:10:3, ::3]

In [ ]:
df

In [ ]:
static.iloc[4:7,[1,2,5]]

In [ ]:
df['Embarked'].value_counts()

In [ ]:
df['Embarked'].value_counts(ascending=True)

In [ ]:
df['Age'].value_counts(sort=False)

In [ ]:
df.sort_values(by='Age', ascending=False)

In [ ]:
df.sort_values(by=['Pclass','Age'], ascending=)

In [ ]:
df=df.set_index(['PassengerId','Age'])

In [ ]:
df

In [ ]:
df=df.reset_index()

In [ ]:
df

In [ ]:
df.rename(index={0:'영번', 1:'일번'}, inplace=True)

In [ ]:
df

In [ ]:
df.pop('부모자식수')

In [ ]:
df=df.drop('가족수', axis=1)
df

In [ ]:
df.drop(drop_cols, axis=1)

In [ ]:
df[df['이름']=='Joseph']

In [ ]:
df[df['이름'].str.contains("")]

In [ ]:
df[df['이름']='Joseph']

In [ ]:
df[df['이름'].str.contains("")

In [ ]:
result=[]
for name in df['이름']:
    result.append(name.replace("(","").replace(")",""))
result
df['이름']=result

In [ ]:
df2=df.copy

In [ ]:
df.columns

In [ ]:
%%time

In [ ]:
df['이름']=df['이름'].str.split(",")

In [ ]:
df['first_name']=df['이름'].apply(lambda x: x[0])
df['second_name']=df['이름'].apply(lambda x: x[1])

In [ ]:
survbysex=df[['성별','생존여부']].groupby(['성별']).value_counts(sort=False)

In [ ]:
df[['성별','생존여부']].groupby(['성별']).mean()

In [ ]:
df[['선실등급','생존여부']].groupby('선실등급').mean()

In [ ]:
df[['성별','나이']].groupby('성별').mean()

In [ ]:
df.pivot_table(values='Survived', index='Sex', columns='Pclass')

In [ ]:
df.dropna()

In [ ]:
round(df['나이'].mean())

In [ ]:
import numpy as np
df[df['나이'].isna()==True].index

In [ ]:
nan_index=df[df['나이'].isna()==True].index

In [ ]:
df['나이']=df['나이'].fillna(round(df['나이'].mean()))

In [ ]:
df['나이']=df['나이'].fillna(df['나이'].mean())

In [ ]:
df.loc[nan_index]

In [ ]:
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb

In [ ]:
engine=create_engine("mysql+pymysql://kict20:kict")
conn=engine.connect()

In [ ]:
passenger=pd.read_sql("p_info", con=conn)
ticket=pd.read_sql("t_info", con=conn)
survived=pd.read_sql("survived", con=conn)
conn.close()

In [ ]:
df_0=pd.concat([passenger, ticket, survived], axis=0)
df_0.iloc[890:893, :]
df_0

In [ ]:
df1=pd.concat([passenger, ticket, survived], axis=1)
df1

In [ ]:
joined_df=pd.merge(passenger, ticket, how="inner", on='PassengerId')

In [ ]:
passenger2=passenger.copy()
passenger2

In [ ]:
passenger2=passenger2.rename(columns={})

In [ ]:
passenger2=passenger2.rename(columns={'PassengerId':'pid'})

In [ ]:
passenger2.columns

In [ ]:
ticket.columns

In [ ]:
pd.merge(passenger2, ticket, how='inner', left_on='pid',)

In [ ]:
passenger=passenger.set_index("PassengerId")

In [ ]:
joined_df2=passengeer.join(ticket, how='inner')
joined_df2

In [ ]:
joined_df2=joined_df2.

In [ ]:
ticket=ticket.set_index("PassengerId")

In [ ]:
engine
conn
passenger3=pd.read_sql("passenger", con=conn)
ticket

In [ ]:
engine=create_engine("mysql+pymysql")
conn=engine.connect()
passenger3=pd.read_sql("passenger", con=conn)
ticket3=pd.read_sql("ticket")

In [ ]:
pd.merge(pd.merge(passenger3, ticket3, on='PassengerId'), ticket3, on='PassengerI')

In [ ]:
toss.duplicated().sum()

In [ ]:
toss=toss.drop_duplicates()