In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import koreanize_matplotlib

In [2]:
data=pd.read_csv("./data/Titanic_train.csv")

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [4]:
data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

# EDA(탐색적 데이터 분석)
* 데이터의 특성, 분포, 변환
* 수치형 데이터와 범주형 데이터를 따로 분석

In [5]:
data['Age']=data['Age'].fillna(data['Age'].mean())

In [6]:
data['Embarked']=data['Embarked'].fillna(data['Embarkded'].mode()[0])

KeyError: 'Embarkded'

In [ ]:
data=data.drop('Cabin', axis=1)

In [ ]:
data.isna().sum

# 범주형 데이터와 수치형 데이터 분리

In [ ]:
data.columns

In [ ]:
categorical=data[['Name','Sex','Ticket','Embarkded']]
numerical=data[['PassengerId', 'Survived','Age', 'SibSp',
       'Parch', 'Fare']]

In [ ]:
categorical_1.describe()

In [ ]:
for cat_cols in categorical_1:
    print(cat_cols)
    print(data[cat_cols].value_counts())

In [ ]:
categorical_1.describe(include='all')

In [ ]:
numerical_1.describe()

dtype을 출력해서 조건문으로 범주형과 수치형 자료를 분리

In [ ]:
categorical_2_cols=[]
numerical_2=[]
for col in data:
    if data[col].dtype =='object':
        categorical_2_cols.append(col)
    else:
        numerical_2_cols.append(col)
print(categorical_2_cols)
print(numerical_2_cols)

In [ ]:
data[numerical_2_cols]

select_dtypes()를 이용한 범주형, 수치형 변수 구분하기

In [ ]:
cate_cols=data.select_dtypes(include=['object'])

In [ ]:
num_cols=data.select_dtypes(exclude=['object'])

In [ ]:
cate_cols

In [ ]:
for col in cate_cols:
    print(cate_cols[col].value_counts())
    print(cate_cols[col].value_counts().plot(kind='bar')

In [ ]:
data.head(1)

In [ ]:
data['PassengerId'].unique()

In [ ]:
data['PassengerId'].describe()

In [ ]:
data['PassengerId'].plot(kind='bar')

In [ ]:
data.columns

In [ ]:
data['Survived'].value_counts()

In [ ]:
data['Survived'].value_counts().plot(kind='pie')

In [ ]:
data['Pclass'].value_counts()

In [ ]:
data['Pclass'].value_counts().plot(kind='bar')

In [ ]:
data['Name'].unique

In [ ]:
data['Sex'].value_counts()

In [ ]:
data['Sex'].value_counts().plot(kind='pie')

In [ ]:
data['Age']

In [ ]:
data['Age'].value_counts()

In [ ]:
data['Age'].plot(kind='hist')

In [ ]:
data.columns

In [ ]:
data['SibSp']

In [ ]:
data['SibSp'].value_counts()

In [ ]:
data['Sibsp'].value_counts.plot(kind='hist')

In [ ]:
data['Parch'].value_counts().plot(kind='bar')

In [ ]:
data['Ticket'].value_counts()

In [ ]:
data['Fare'].value_counts()

In [ ]:
data['Fare'].plot(kind='hist')

In [ ]:
fare_desc=data['Fare'].describe()

In [ ]:
maximum=fare_desc.loc['75%']+(1.5*(fare_desc.loc['75%']-fare_desc.loc['25%']))

In [ ]:
outliers=data[data['Fare']> maximum]
outliers

Fare를 Pclass 별로 나누어 확인

In [ ]:
pc_fare_desc=data[['Pclass', 'Fare']].groupby('Pclass').describe()
pc_fare_desc

In [ ]:
pc_fare_desc.columns

In [ ]:
pc1_max=pclass_1_max=pc_fare_desc.loc[1, ('Fare', '75%') + (1.5 * pc_fare_desc.loc[1, ('Fare', '25%')])]
pc1_max=pclass_1_max=pc_fare_desc.loc[2, ('Fare', '75%') + (1.5 * pc_fare_desc.loc[1, ('Fare', '25%')])]

In [ ]:
data[(data['Pclass']==1) & (data['Fare']>pc1_max)]

In [ ]:
data['Embarked'].value_counts()

# 종속 변수(Survived)와 독립변수(Survived를 제외한 나머지) 관계 파악하기 groupby

In [ ]:
data.columns

* Pclass는 생존율에 영향을 미침. 1이면 높고 3이면 낮다

In [ ]:
data[['Pclass','Survived']].groupby("Pclass").mean()

In [ ]:
data[['Name','Survived']].groupby("Name").mean()

In [ ]:
* 성별별 생존율: 여자가 남자보다 생존율이 높다.

In [ ]:
data[['Sex','Survived']].groupby("Sex").mean()

In [ ]:
data[['Age','Survived']].groupby("Age").mean()

* 나이를 구간화해서 생존율과의 관계 파악
    * 10, 20, 30, 40, 50
    * 0 -10 under10s
    * 10-19 10s
    * 20-29 20s

In [ ]:
def age_cat(x):
    if x < 10:
        return "under10s"
    elif 10 <=x<20:
        return "10s"
    elif 20 <=x<30:
        return "20s"
    elif 30 <=x<40:
        return "30s"
    elif 40 <=x<50:
        return "40s"
    elif 50 <=x<60:
        return "50s"
    elif 60 <=x<70:
        return "60s"
    elif 70 <=x<80:
        return "80s"
    elif 80 <=x<90:
        return "80s"

In [ ]:
data['age_cat']=data['Age'].apply(age_cat)
data.head()

연령대별 생존율 구하기

In [ ]:
data[['age_cat','Survived']].groupby('age_cat').mean().sort_values(by='Survived', ascending=False)

In [ ]:
data[['SibSp','Survived']].groupby('SibSp').mean().sor_values(by="Survived", ascending=False)

In [ ]:
data[['Parch','Survived']].groupby('Parch').mean().sor_values(by="Survived", ascending=False)

In [ ]:
data[['Embarkded','Survived']].groupby('Embarkded').mean().sor_values(by="Survived", ascending=False)

* pclass, sex, age_cat

In [ ]:
data[['Pclass','Sex','Survived']].groupby(['Pclass','Sex']).mean()

In [ ]:
data[['Pclass','Sex','age_cat','Survived']].groupby(['Pclass','Sex','age_cat']).mean().sort_values(by='Survived', ascending=False)

* 데이터의 구간화를 쉽게 해주는 함수 cut
* cut(data['Age'], bins=[구간], labels['구간의 이름'])

In [ ]:
data['age_cat2']=pd.cut(data['Age'], 
       bins=[0,10, 20, 30, 40, 50, 60, 70, 80, 90],
      labels=['under10s', '10s', '20s', '30s','40s','50s','60s','70s','80s'])

In [ ]:
data[['age_cat','age_cat2']]

# 변수들 간의 상관관계 보기 .corr()
* .corr()
* -1 0 1
* -1: 음의 상관관계(반비례 관계, 집과 역의 거리가 멀면 집값이 떨어진다)
* 0: 관계 없음
* 1: 양의 상관관계

In [ ]:
data.columns

In [ ]:
data[['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp',
       'Parch','Fare']].corr()

# 데이터 전처리를 안하고 알고리즘에 넣었을 때 생기는 일

In [7]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [8]:
df = pd.read_csv("./data/Titanic_train.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [9]:
# x는 독립변수 y는 종속변수
X = df.drop('Survived', axis=1)
y = df['Survived']

In [10]:
X

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=7)

In [12]:
dct=DecisionTreeClassifier()
dct.fit(X_train, y_train)
pred=dct.predict(X_test)
print()

ValueError: could not convert string to float: 'Andersen-Jensen, Miss. Carla Christine Nielsine'

# Feature Engineering
* 필요없는 변수 삭제
* 필요한 변수만 선택
* 새로운 변수 생성(파생변수)
* 카테고리 변수에 대한 label encoding, one-hot encoding

# 문자로 되어 있는 범주형 자료를 숫자로 변환하기
* 조건문을 이용해서 숫자로 변환하기. 서열 있음
* label encoding을 이용해서 변환하기 - 나중에 숫자에서 문자로 복원 가능. 서열 있음
* one-hot encoding unique value의 개수만큼 새로운 컬럼을 만들어서 0과 1로 구분, 서열이 사라지고 평등해짐.

In [13]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [14]:
df['Embarked']=df['Embarked'].fillna(df['Embarked'].mode()[0])

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [16]:
df=df.drop(['PassengerId','Name','Cabin'], axis=1)

In [17]:
df=df.drop(['Ticket'], axis=1)
df

     Survived  Pclass     Sex        Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.000000      1      0   7.2500        S
1           1       1  female  38.000000      1      0  71.2833        C
2           1       3  female  26.000000      0      0   7.9250        S
3           1       1  female  35.000000      1      0  53.1000        S
4           0       3    male  35.000000      0      0   8.0500        S
..        ...     ...     ...        ...    ...    ...      ...      ...
886         0       2    male  27.000000      0      0  13.0000        S
887         1       1  female  19.000000      0      0  30.0000        S
888         0       3  female  29.699118      1      2  23.4500        S
889         1       1    male  26.000000      0      0  30.0000        C
890         0       3    male  32.000000      0      0   7.7500        Q

[891 rows x 8 columns]

In [18]:
df.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='object')

In [19]:
# 파생변수 생성하기 형제자매 컬럼과 부모자식 컬럼을 합쳐서 가족 컬럼생성
df['Family']=df['SibSp']+df['Parch']
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Family
0,0,3,male,22.000000,1,0,7.2500,S,1
1,1,1,female,38.000000,1,0,71.2833,C,1
2,1,3,female,26.000000,0,0,7.9250,S,0
3,1,1,female,35.000000,1,0,53.1000,S,1
4,0,3,male,35.000000,0,0,8.0500,S,0
...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,0
887,1,1,female,19.000000,0,0,30.0000,S,0
888,0,3,female,29.699118,1,2,23.4500,S,3
889,1,1,male,26.000000,0,0,30.0000,C,0
890,0,3,male,32.000000,0,0,7.7500,Q,0

In [20]:
df.drop(['SibSp','Parch'], axis=1)

     Survived  Pclass     Sex        Age     Fare Embarked  Family
0           0       3    male  22.000000   7.2500        S       1
1           1       1  female  38.000000  71.2833        C       1
2           1       3  female  26.000000   7.9250        S       0
3           1       1  female  35.000000  53.1000        S       1
4           0       3    male  35.000000   8.0500        S       0
..        ...     ...     ...        ...      ...      ...     ...
886         0       2    male  27.000000  13.0000        S       0
887         1       1  female  19.000000  30.0000        S       0
888         0       3  female  29.699118  23.4500        S       3
889         1       1    male  26.000000  30.0000        C       0
890         0       3    male  32.000000   7.7500        Q       0

[891 rows x 7 columns]

* 반복문과 조건문을 이용해서 바꾸기

In [21]:
result=[]
for i in df['Sex']:
    if i == 'male':
        result.append(0)
    else:
        result.append(1)
df['Sex2']= result
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Family,Sex2
0,0,3,male,22.000000,1,0,7.2500,S,1,0
1,1,1,female,38.000000,1,0,71.2833,C,1,1
2,1,3,female,26.000000,0,0,7.9250,S,0,1
3,1,1,female,35.000000,1,0,53.1000,S,1,1
4,0,3,male,35.000000,0,0,8.0500,S,0,0
...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,0,0
887,1,1,female,19.000000,0,0,30.0000,S,0,1
888,0,3,female,29.699118,1,2,23.4500,S,3,1
889,1,1,male,26.000000,0,0,30.0000,C,0,0
890,0,3,male,32.000000,0,0,7.7500,Q,0,0

* .str.replace

In [22]:
df['Sex3']=df['Sex'].str.replace("female","1").str.replace("male","0")
df['Sex3']=df['Sex3'].astype(int)
df['Sex3'].dtype

dtype('int64')

In [23]:
df['Sex'].apply(lambda x: 0 if x=='male' else 1)

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    1
889    0
890    0
Name: Sex, Length: 891, dtype: int64

label encoder를 이용해서 변경하는 방법

In [24]:
from sklearn.preprocessing import LabelEncoder

In [25]:
le=LabelEncoder()
sex_le=le.fit_transform(df['Sex'])
sex_le

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1])

In [26]:
df['sex_le']=sex_le
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Family,Sex2,Sex3,sex_le
0,0,3,male,22.000000,1,0,7.2500,S,1,0,0,1
1,1,1,female,38.000000,1,0,71.2833,C,1,1,1,0
2,1,3,female,26.000000,0,0,7.9250,S,0,1,1,0
3,1,1,female,35.000000,1,0,53.1000,S,1,1,1,0
4,0,3,male,35.000000,0,0,8.0500,S,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,0,0,0,1
887,1,1,female,19.000000,0,0,30.0000,S,0,1,1,0
888,0,3,female,29.699118,1,2,23.4500,S,3,1,1,0
889,1,1,male,26.000000,0,0,30.0000,C,0,0,0,1
890,0,3,male,32.000000,0,0,7.7500,Q,0,0,0,1

In [27]:
le.inverse_transform(sex_le)

array(['male', 'female', 'female', 'female', 'male', 'male', 'male',
       'male', 'female', 'female', 'female', 'female', 'male', 'male',
       'female', 'female', 'male', 'male', 'female', 'female', 'male',
       'male', 'female', 'male', 'female', 'female', 'male', 'male',
       'female', 'male', 'male', 'female', 'female', 'male', 'male',
       'male', 'male', 'male', 'female', 'female', 'female', 'female',
       'male', 'female', 'female', 'male', 'male', 'female', 'male',
       'female', 'male', 'male', 'female', 'female', 'male', 'male',
       'female', 'male', 'female', 'male', 'male', 'female', 'male',
       'male', 'male', 'male', 'female', 'male', 'female', 'male', 'male',
       'female', 'male', 'male', 'male', 'male', 'male', 'male', 'male',
       'female', 'male', 'male', 'female', 'male', 'female', 'female',
       'male', 'male', 'female', 'male', 'male', 'male', 'male', 'male',
       'male', 'male', 'male', 'male', 'female', 'male', 'female', 'male',
       'male', 'male', 'male', 'male', 'female', 'male', 'male', 'female',
       'male', 'female', 'male', 'female', 'female', 'male', 'male',
       'male', 'male', 'female', 'male', 'male', 'male', 'female', 'male',
       'male', 'male', 'male', 'female', 'male', 'male', 'male', 'female',
       'female', 'male', 'male', 'female', 'male', 'male', 'male',
       'female', 'female', 'female', 'male', 'male', 'male', 'male',
       'female', 'male', 'male', 'male', 'female', 'male', 'male', 'male',
       'male', 'female', 'male', 'male', 'male', 'male', 'female', 'male',
       'male', 'male', 'male', 'female', 'female', 'male', 'male', 'male',
       'male', 'female', 'male', 'male', 'male', 'male', 'female', 'male',
       'male', 'female', 'male', 'male', 'male', 'female', 'male',
       'female', 'male', 'male', 'male', 'female', 'male', 'female',
       'male', 'female', 'female', 'male', 'male', 'female', 'female',
       'male', 'male', 'male', 'male', 'male', 'female', 'male', 'male',
       'female', 'male', 'male', 'female', 'male', 'male', 'male',
       'female', 'female', 'male', 'female', 'male', 'male', 'male',
       'male', 'male', 'male', 'male', 'male', 'male', 'male', 'female',
       'female', 'male', 'male', 'female', 'male', 'female', 'male',
       'female', 'male', 'male', 'female', 'female', 'male', 'male',
       'male', 'male', 'female', 'female', 'male', 'male', 'male',
       'female', 'male', 'male', 'female', 'female', 'female', 'female',
       'female', 'female', 'male', 'male', 'male', 'male', 'female',
       'male', 'male', 'male', 'female', 'female', 'male', 'male',
       'female', 'male', 'female', 'female', 'female', 'male', 'male',
       'female', 'male', 'male', 'male', 'male', 'male', 'male', 'male',
       'male', 'male', 'female', 'female', 'female', 'male', 'female',
       'male', 'male', 'male', 'female', 'male', 'female', 'female',
       'male', 'male', 'female', 'male', 'male', 'female', 'female',
       'male', 'female', 'female', 'female', 'female', 'male', 'male',
       'female', 'female', 'male', 'female', 'female', 'male', 'male',
       'female', 'female', 'male', 'female', 'male', 'female', 'female',
       'female', 'female', 'male', 'male', 'male', 'female', 'male',
       'male', 'female', 'male', 'male', 'male', 'female', 'male', 'male',
       'male', 'female', 'female', 'female', 'male', 'male', 'male',
       'male', 'male', 'male', 'male', 'male', 'female', 'female',
       'female', 'female', 'male', 'male', 'female', 'male', 'male',
       'male', 'female', 'female', 'female', 'female', 'male', 'male',
       'male', 'male', 'female', 'female', 'female', 'male', 'male',
       'male', 'female', 'female', 'male', 'female', 'male', 'male',
       'male', 'female', 'male', 'female', 'male', 'male', 'male',
       'female', 'female', 'male', 'female', 'male', 'male', 'female',
       'male', 'male', 'female', 'male', 'female', 'male', 'male', 'male',
       'male', 'female', 'male', 'male', 'female', 'male', 'male',
       'female', 'female', 'female', 'male', 'female', 'male', 'male',
       'male', 'female', 'male', 'male', 'female', 'female', 'male',
       'male', 'male', 'female', 'female', 'male', 'male', 'female',
       'female', 'female', 'male', 'male', 'female', 'male', 'male',
       'female', 'male', 'male', 'female', 'male', 'female', 'male',
       'male', 'male', 'male', 'male', 'male', 'male', 'male', 'female',
       'female', 'male', 'male', 'male', 'male', 'male', 'male', 'male',
       'male', 'male', 'male', 'female', 'male', 'male', 'female',
       'female', 'female', 'male', 'male', 'male', 'male', 'female',
       'male', 'male', 'male', 'female', 'male', 'female', 'female',
       'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male',
       'male', 'female', 'male', 'female', 'male', 'male', 'female',
       'female', 'female', 'female', 'male', 'female', 'male', 'male',
       'male', 'male', 'male', 'male', 'female', 'male', 'male', 'female',
       'male', 'female', 'male', 'female', 'male', 'male', 'female',
       'male', 'male', 'female', 'male', 'male', 'male', 'female', 'male',
       'male', 'female', 'female', 'female', 'male', 'female', 'male',
       'female', 'female', 'female', 'female', 'male', 'male', 'male',
       'female', 'male', 'male', 'male', 'male', 'male', 'male', 'male',
       'female', 'male', 'female', 'male', 'female', 'female', 'male',
       'male', 'male', 'male', 'female', 'male', 'male', 'female', 'male',
       'male', 'male', 'female', 'male', 'female', 'male', 'male',
       'female', 'female', 'female', 'male', 'female', 'female', 'male',
       'male', 'male', 'female', 'male', 'male', 'male', 'male', 'male',
       'female', 'male', 'female', 'male', 'male', 'female', 'male',
       'male', 'male', 'female', 'male', 'male', 'male', 'male', 'male',
       'male', 'male', 'female', 'female', 'female', 'male', 'female',
       'male', 'male', 'female', 'male', 'female', 'female', 'male',
       'male', 'male', 'male', 'male', 'male', 'male', 'male', 'female',
       'male', 'male', 'male', 'male', 'male', 'male', 'female', 'female',
       'male', 'male', 'female', 'male', 'male', 'female', 'female',
       'male', 'female', 'male', 'male', 'male', 'male', 'female', 'male',
       'female', 'male', 'female', 'female', 'male', 'male', 'female',
       'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male',
       'male', 'male', 'male', 'female', 'female', 'male', 'male', 'male',
       'male', 'male', 'male', 'female', 'female', 'male', 'female',
       'male', 'male', 'male', 'male', 'male', 'male', 'male', 'male',
       'female', 'male', 'female', 'male', 'male', 'male', 'male', 'male',
       'female', 'male', 'male', 'female', 'male', 'female', 'male',
       'male', 'male', 'female', 'male', 'female', 'male', 'female',
       'male', 'male', 'male', 'male', 'male', 'female', 'female', 'male',
       'male', 'female', 'male', 'male', 'male', 'male', 'male', 'female',
       'female', 'male', 'female', 'female', 'male', 'male', 'male',
       'male', 'male', 'female', 'male', 'male', 'male', 'male', 'male',
       'female', 'male', 'male', 'male', 'male', 'female', 'male', 'male',
       'female', 'male', 'male', 'male', 'female', 'male', 'male', 'male',
       'male', 'female', 'male', 'male', 'male', 'female', 'male',
       'female', 'male', 'female', 'male', 'male', 'male', 'male',
       'female', 'male', 'female', 'male', 'male', 'female', 'male',
       'female', 'female', 'female', 'male', 'male', 'male', 'male',
       'female', 'male', 'male', 'male', 'male', 'male', 'female', 'male',
       'male', 'male', 'female', 'female', 'male', 'female', 'male',
       'female', 'male', 'male', 'male', 'male', 'male', 'female', 'male',
       'female', 'male', 'male', 'male', 'female', 'male', 'male',
       'female', 'male', 'male', 'male', 'female', 'male', 'male',
       'female', 'male', 'male', 'male', 'male', 'male', 'female',
       'female', 'male', 'male', 'male', 'male', 'female', 'male', 'male',
       'male', 'male', 'male', 'male', 'female', 'male', 'male', 'male',
       'male', 'male', 'male', 'female', 'male', 'male', 'female',
       'female', 'female', 'female', 'female', 'male', 'female', 'male',
       'male', 'male', 'female', 'female', 'male', 'female', 'female',
       'male', 'male', 'male', 'male', 'female', 'male', 'male', 'female',
       'female', 'male', 'male', 'male', 'female', 'female', 'male',
       'female', 'male', 'male', 'female', 'male', 'female', 'female',
       'male', 'male'], dtype=object)

* one-hot encoding
* value의 개수만큼 새로운 컬럼(변수)을 만들어서 0과 1로 표시
* 자료의 서열이 사라짐
* 더미변수 만들기, get_dummies()
* value가 너무 많으면 변수의 수가 너무 많이 증가하는 문제 발생
* 변수가 너무 낳이 늘어나면 다중공선성(변수들이 너무 비슷한 얘들이 많음)문제 발생.
* get_dummies(df, drop_first=True)

In [28]:
df2=pd.get_dummies(df, columns=['Sex','Family','Embarked'], drop_first=True)

In [29]:
X=df2.drop(['Survived', 'Fare', 'Sex2','Sex3','sex_le'], axis=1)
X

,Pclass,Age,SibSp,Parch,Sex_male,Family_1,Family_2,Family_3,Family_4,Family_5,Family_6,Family_7,Family_10,Embarked_Q,Embarked_S
0,3,22.000000,1,0,True,True,False,False,False,False,False,False,False,False,True
1,1,38.000000,1,0,False,True,False,False,False,False,False,False,False,False,False
2,3,26.000000,0,0,False,False,False,False,False,False,False,False,False,False,True
3,1,35.000000,1,0,False,True,False,False,False,False,False,False,False,False,True
4,3,35.000000,0,0,True,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,2,27.000000,0,0,True,False,False,False,False,False,False,False,False,False,True
887,1,19.000000,0,0,False,False,False,False,False,False,False,False,False,False,True
888,3,29.699118,1,2,False,False,False,True,False,False,False,False,False,False,True
889,1,26.000000,0,0,True,False,False,False,False,False,False,False,False,False,False
890,3,32.000000,0,0,True,False,False,False,False,False,False,False,False,True,False

In [30]:
y= df2['Survived']
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10)

In [ ]:
print(len(X_train), len(X_test))
print(len(y_train), len(y_test))
X_train.head()

In [32]:
dtc=DecisionTreeClassifier()
dtc.fit(X_train, y_train)
pred=dtc.predict(X_test)
print(y_test, pred)
pd.DataFrame([y_test, T, pred.T], columns=["y_test","pred"])

590    0
131    0
628    0
195    1
230    1
      ..
318    1
863    0
254    0
396    0
358    1
Name: Survived, Length: 268, dtype: int64 [0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 1 0 1 1 0 1 0 1 0 0
 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 1 1 0 1 1 0 0 1 1 0 0 0 1 0 0 1 0 0 0 1
 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 0 0 0 1 0 1 1 0 0 1 1 0 0 1 0 1
 0 1 0 0 0 1 1 1 1 1 0 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 0 1 0 1 0 0 0 0 0 1 0
 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 1 0 1 1 0 1 0 0 0 0 0 1 0 1 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0 1 0 0 0 1 1 0 0 0 1 0
 1 1 1 1 0 0 1 1 0 1 0 0 1 0 0 1 0 1 1 1 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 1
 0 0 0 1 1 0 0 1 1]

NameError: name 'T' is not defined

# 모델의 성능 테스트

In [ ]:
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
print(accuracy_score(y_test, pred))

In [ ]:
print(classification_report(y_test, pred))

# 상관관계 분석 .corr()
* 변수들 간의 상관관계 분석
* 1이면 강한 양의 상관관계
* -1이면 강한 음의 상관관계
* 0이면 관계가 없음
* 0.5나 -0.5면 고묀
* 0.7이상이면 두 변수 중 한개만 선택
* method='pearson': 숫자형 데이터들 간의 상관관계 분석
* method='spearman': 범주형 데이터가 섞여 있는 데이터셋의 경우 스피어만으로 상관관계 분석

In [ ]:
df2.corr(method='spearman')

* 상관관계를 보여주는 그래프: heatmap

In [ ]:
import seaborn as sns

In [ ]:
plt.figure(figsize=(20,20))
sns.heatmap(df2.corr(method='spearman').annot=True, linewidth=0.5)

# 연습

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_scroe, classification_report

In [33]:
rfc=RandomForestClassifier(random_state=10)
rfc.fit(X_train, y_train)
pred=rfc.predict(X_test)
print(accuracy_score(y_test, pred))
print(classification_report(y_test,pred)

SyntaxError: unexpected EOF while parsing (2159992214.py, line 5)

In [ ]:
from sklearn.linear_model import LogisticRegression