# 찾을 자료 1개씩 찾아보기

In [ ]:
soup.select("tbody > tr")[0].select_one("td:nth-child(1)")

In [ ]:
# 주식종목
soup.select("tbody > tr")[0].select_one("td:nth-child(1)>img")['alt']

In [ ]:
# 회사이름
soup.select("tbody > tr")[0].select_one("td:nth-child(1)>a")['title']

In [ ]:
# 종목코드
soup.select("tbody > tr")[0].select_one("td:nth-child(1)>a")["onclick"].split("'")[1]

In [ ]:
# 업종
soup.select("tbody > tr")[0].select_one("td:nth-child(2)").text

In [ ]:
# 주요제품
soup.select("tbody > tr")[0].select_one("td:nth-child(3)").text

In [ ]:
# 상장일
soup.select("tbody > tr")[0].select_one("td:nth-child(4)").text

In [ ]:
# 결산월
soup.select("tbody > tr")[0].select_one("td:nth-child(5)").text

In [ ]:
# 대표자명
soup.select("tbody > tr")[0].select_one("td:nth-child(6)").text

In [ ]:
# 홈페이지(url)
soup.select("tbody > tr")[0].select_one("td:nth-child(7)>a")['href']

In [ ]:
# 지역
soup.select("tbody > tr")[0].select_one("td:nth-child(8)").text

In [ ]:
# 전체 페이지
total_page=int(soup.select_one(".info.type-00 > em").text.replace(",","")) // 100 + 1

In [ ]:
# 컬럼명
columns= soup.select_one("table")['summary'].split(", ")
columns.insert(0,"주식종목")
columns.insert(2,"종목코드")
print(columns)
df=pd.DataFrame(company_infos, columns=columns)
columns

# 코드 합쳐서 1페이지 정보 모두 추출하기

In [3]:
import requests
import time
import pandas as pd
from bs4 import BeautifulSoup as bs

In [4]:
https://kind.krx.co.kr/corpgeneral/corpList.do?method=searchCorpList&pageIndex=2&currentPageSize=100&comAbbrv=&beginIndex=&orderMode=3&orderStat=D&isurCd=&repIsuSrtCd=&searchCodeType=&marketType=&searchType=13&industry=&fiscalYearEnd=all&comAbbrvTmp=&location=all#

SyntaxError: invalid syntax (734501192.py, line 1)

In [5]:
url="https://kind.krx.co.kr/corpgeneral/corpList.do"

In [6]:
payload=dict(method="searchCorpList", pageIndex=2, currentPageSize=100, comAbbrv=, orderMode=3, orderStat="D", isurCd=, repIsuSrtCd=, searchCodeType=, marketType=, searchType=13, industry=, fiscalYearEnd="all", comAbbrvTmp=, location="all")

SyntaxError: invalid syntax (3452764770.py, line 1)

In [7]:
r=requests.post(url, data=payload)
print(r.url)
print(r.status_code)
soup=bs(r.content, 'lxml')
soup

NameError: name 'payload' is not defined

# 찾을 자료 1개씩 찾기

In [8]:
soup.select("tbody>tr")

NameError: name 'soup' is not defined

In [9]:
soup.select("tbody>tr")[0].select_one("td:nth-child(1)")

NameError: name 'soup' is not defined

In [ ]:
soup.select("tbody>tr")[0].select_one("td:nth-child(1)>img")['alt']

In [ ]:
soup.select("tbody>tr")[0].select_one("td:nth-child(1)> a")['onclick'].split("'")[1]

In [ ]:
# 업종
soup.select("tbody>tr")[0].select_one("td:nth-child(2)")

In [ ]:
soup.select("tbody>tr")[0].select_one("td:nth-child(3)")

In [ ]:
soup.select("tbody>tr")[0].select_one("td:nth-child(4)")

In [ ]:
soup.select("tbody>tr")[0].select_one("td:nth-child(5)")

In [ ]:
soup.select("tbody>tr")[0].select_one("td:nth-child(6)").text

In [ ]:
soup.select("tbody>tr")[0].select_one("td:nth-child(7)")

In [ ]:
soup.select("tbody>tr")[0].select_one("td:nth-child(8)").text

In [ ]:
total_page=int(soup.select_one(".info.type-00>em").text.replace(",",""))//100+1
total_page

In [ ]:
soup.select_one("table")['summary'].split(",")

In [ ]:
columns=soup.select_one("table")['summary'].split(",")
columns.insert(0, "주식종목")
columns.insert(2, "종목코드")
columns

In [ ]:
for idx, tr in enumerate(soup.select("tbody > tr")):
    print(f'{idx}/{len(soup.select("tbody > tr"))} 작업중')
    # 주식종목
    stock_type = tr.select_one("td:nth-child(1) > img")['alt'])
    # 회사이름
    company_name = tr.select_one("td:nth-child(1) > a")["title"])
    # 종목코드
    stock_code = tr.select_one("td:nth-child(1) > a")["onclick"].split("'")[1])
    # 업종
    business_type = tr.select_one("td:nth-child(2)").text)
    # 주요제품
    product = tr.select_one("td:nth-child(3)").text)
    # 상장일
    resi_date = tr.select_one("td:nth-child(4)").text)
    # 결산월
    settlement = tr.select_one("td:nth-child(5)").text)
    # 대표자명
    ceo = tr.select_one("td:nth-child(6)").text)
    # 홈페이지(url)
    hompage = tr.select_one("td:nth-child(7) > a")["href"] if tr.select_one("td:nth-child(7) > a") != None else "")
    # 지역
    region = tr.select_one("td:nth-child(8)").text)

# 코드 합쳐서 1페이지 정보 모두 추출하기

In [ ]:
import requests
import time
import pandas as pd
from bs4 import BeautifulSoup as bs

In [ ]:
url ="https://kind.krx.co.kr/corpgeneral/corpList.do"
payload = dict(method="searchCorpList", pageIndex=1, currentPageSize=100, orderMode=3, orderStat="D", searchType=13, fiscalYearEnd="all", location="all")
r = requests.post(url, data=payload)
print(r.status_code)
soup = bs(r.content, 'lxml')
company_infos = []
for idx, tr in enumerate(soup.select("tbody > tr")):
    print(f'{idx}/{len(soup.select("tbody > tr"))} 작업중')
    # 주식종목
    stock_type = tr.select_one("td:nth-child(1) > img")['alt']
    # 회사이름
    company_name = tr.select_one("td:nth-child(1) > a")["title"]
    # 종목코드
    stock_code = tr.select_one("td:nth-child(1) > a")["onclick"].split("'")[1]
    # 업종
    business_type = tr.select_one("td:nth-child(2)").text
    # 주요제품
    product = tr.select_one("td:nth-child(3)").text
    # 상장일
    resi_date = tr.select_one("td:nth-child(4)").text
    # 결산월
    settlement = tr.select_one("td:nth-child(5)").text
    # 대표자명
    ceo = tr.select_one("td:nth-child(6)").text
    # 홈페이지(url)
    hompage = tr.select_one("td:nth-child(7) > a")["href"] if tr.select_one("td:nth-child(7) > a") != None else ""
    # 지역
    region = tr.select_one("td:nth-child(8)").text
    company_infos.append((stock_type, company_name, stock_code, business_type,
                        product, resi_date, settlement, ceo, hompage, region))
company_infos

# 전체 페이지 데이터 수집하기

In [12]:
import requests
import time
import pandas as pd
from bs4 import BeautifulSoup as bs

In [13]:
company_infos = []
page = 1
while True:
    url ="https://kind.krx.co.kr/corpgeneral/corpList.do"
    payload = dict(method="searchCorpList", pageIndex=page,
                 currentPageSize=100,
                 orderMode=3, orderStat="D", searchType=13,
                 fiscalYearEnd="all", location="all")
    r = requests.post(url, data=payload)
#     print(r.status_code)
    soup = bs(r.content, 'lxml')
    # 전체 페이지
    total_page = int(soup.select_one(".info.type-00 > em").text.replace(",", "")) // 100 + 1
    
    for idx, tr in enumerate(soup.select("tbody > tr")):
        print(f'{page}/{total_page}중, {idx}/{len(soup.select("tbody > tr"))} 작업중', end="\r")
        # 주식종목
        stock_type = tr.select_one("td:nth-child(1) > img")['alt']
        # 회사이름
        company_name = tr.select_one("td:nth-child(1) > a")["title"]
        # 종목코드
        stock_code = tr.select_one("td:nth-child(1) > a")["onclick"].split("'")[1]
        # 업종
        business_type = tr.select_one("td:nth-child(2)").text
        # 주요제품
        product = tr.select_one("td:nth-child(3)").text
        # 상장일
        resi_date = tr.select_one("td:nth-child(4)").text
        # 결산월
        settlement = tr.select_one("td:nth-child(5)").text
        # 대표자명
        ceo = tr.select_one("td:nth-child(6)").text
        # 홈페이지(url)
        hompage = tr.select_one("td:nth-child(7) > a")["href"] if tr.select_one("td:nth-child(7) > a") != None else ""
        # 지역
        region = tr.select_one("td:nth-child(8)").text
        company_infos.append((stock_type, company_name, stock_code, business_type,
                            product, resi_date, settlement, ceo, hompage, region))

    if page < total_page:
        page += 1
    else:
        break
    
# 컬럼명
columns = soup.select_one("table")["summary"].split(", ")
columns.insert(0, "주식종목")
columns.insert(2, "종목코드")
print(columns)
df = pd.DataFrame(company_infos, columns=columns)
df

['주식종목', '회사명', '종목코드', '업종', '주요제품', '상장일', '결산월', '대표자명', '홈페이지', '지역']

,주식종목,회사명,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역
0,코스닥,한국피아이엠,44890,자동차 신품 부품 제조업,"내연기관 부품(터보차저, DCT변속기), IT 부품(스마트워치/스마트링), 자율주행...",2025-04-04,12월,송준호,http://www.pimkorea.com,대구광역시
1,코스닥,에이유브랜즈,48107,"섬유, 의복, 신발 및 가죽제품 소매업","레인부츠, 스니커즈, 겨울화, 패션잡화 등",2025-04-03,12월,김지훈,http://aubrandz.irpage.co.kr,서울특별시
2,코스닥,우양에이치씨,10197,"구조용 금속제품, 탱크 및 증기발생기 제조업","화공 플랜트, 에너지 플랜트",2025-03-28,12월,김진태,http://www.wooyang.co.kr,경기도
3,코스닥,더즌,46286,전기 통신업,디지털뱅킹 솔루션(B2B 금융 서비스),2025-03-24,12월,조철한,http://www.dozn.co.kr/,서울특별시
4,코스닥,심플랫폼,44453,소프트웨어 개발 및 공급업,NUBISON AIoT(산업용 데이터 수집과 산업용 AI서비스 운영),2025-03-21,12월,임대근..,http://simplatform.com/,서울특별시
...,...,...,...,...,...,...,...,...,...,...
2756,유가증권,유한양행,00010,의약품 제조업,"의약품(삐콤씨, 안티푸라민, 렉라자, 로수바미브, 코푸시럽 등), 생활용품(유한락스...",1962-11-01,12월,대표이..,http://www.yuhan.co.kr,서울특별시
2757,유가증권,CJ대한통운,00012,도로 화물 운송업,"Contract Logistics, 포워딩, 항만하역, 해운, 택배국제특송, SCM...",1956-07-02,12월,신영수..,http://www.cjlogistics.com,서울특별시
2758,유가증권,경방,00005,종합 소매업,"섬유류(면사,면혼방사,면직물,면혼방직물,화섬사,화섬직물) 제조,도매,수출입",1956-03-03,12월,"김준,..",http://www.kyungbang.co.kr,서울특별시
2759,유가증권,유수홀딩스,00070,회사 본부 및 경영 컨설팅 서비스업,지주사업,1956-03-03,12월,송영규,http://www.eusu-holdings.com,서울특별시
2760,유가증권,한진중공업홀딩스,00348,연료용 가스 제조 및 배관공급업,지주회사,1956-03-03,12월,조원국,http://www.hhic-holdings.com,경기도

# 데이터를 수집한 날짜를 포함해서 파일명을 만들고 저장하기

In [18]:
from datetime import datetime

In [19]:
today = datetime.now()
today = f"{today.year}_{today.month:02d}_{today.day:02d}"

In [20]:
df.to_csv(f"./scraping_results/상장기업정보_{today}기준.csv", encoding="utf-8", index=False)

OSError: Cannot save file into a non-existent directory: 'scraping_results'

# 수집한 자료를 데이터베이스에 저장하기

In [21]:
!pip install PyMySQL

Requirement already satisfied: PyMySQL in c:\users\admin\miniforge3\envs\fintech\lib\site-packages (1.1.1)

In [ ]:
# DB에 접속하는 라이브러리: !pip install sqlalchemy
# SQL 중 MYSQL에 접속하는 라이브러리!pip install PyMySQL

In [22]:
from sqlalchemy import create_engine, text
import pymysql
pymysql.install_as_MySQLdb()

In [23]:
# sqlalchemy의 create_engine을 이용해서 mysql 서버에 접속. engine을 실행하는 순간 workbench를 열었다고 생각하면 됨
engine = create_engine("mysql+pymysql://root:1234@localhost:3306/stock_info")
# engine.connect create_engine에 있는 정보로 DB접속
conn=engine.connect()

In [24]:
# 데이터프레임을 DB에 저장하기
# 데이터프레임명.to_sql("테이블명")
df.to_sql("stock_company_info_{today}", con=conn, if_exists='replace', index=False)
conn.close()

# 판다스의 read_html를 이용해서 table 자료 한 번에 가져오기

In [26]:
soup.select_one("table")

<table class="list type-00 tmt30" summary="회사명, 업종, 주요제품, 상장일, 결산월, 대표자명, 홈페이지, 지역">
<caption>목록</caption>
<colgroup>
<col width="*"/>
<col width="15%"/>
<col width="20%"/>
<col width="11%"/>
<col width="8%"/>
<col width="10%"/>
<col width="8%"/>
<col width="12%"/>
</colgroup>
<thead>
<tr class="first" id="title-contents">
</tr>
</thead>
<tbody>
<tr class="first">
<td class="first" title="(주)디에이치오토넥스"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00030'); return false;" title="DH오토넥스"> DH오토넥스</a> <img alt="관리종목" class="vmiddle legend" src="/images/common/icn_t_kwan.gif"/> </td>
<td class="textOverflow" title="통신 및 방송 장비 제조업">통신 및 방송 장비 제조업</td>
<td class="textOverflow" title="유,무선 통신장비">유,무선 통신장비</td>
<td class="txc">1975-06-09</td>
<td class="txc">12월</td>
<td class="txc" title="최준용">최준용</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.dayouplus.co.kr" target="_blank" title="http://www.dayouplus.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">전북특별자치도</td>
</tr>
<tr>
<td class="first" title="(주)BYC"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00146'); return false;" title="BYC"> BYC</a> </td>
<td class="textOverflow" title="봉제의복 제조업">봉제의복 제조업</td>
<td class="textOverflow" title="메리야스,란제리 제조,도매/건축공사/부동산 임대,분양,공급">메리야스,란제리 제조,도매/건축공사/부동산 임대,분양,공급</td>
<td class="txc">1975-06-02</td>
<td class="txc">12월</td>
<td class="txc" title="김 대 환">김 대..</td>
<td class="txc">
<a class="btn ico homepage" href="http://home.byc.co.kr" target="_blank" title="http://home.byc.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="케이지모빌리티(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00362'); return false;" title="KG모빌리티"> KG모빌리티</a> <img alt="KOSPI200" class="vmiddle legend" src="/images/common/icn_t_k200.gif"/> <img alt="KRX300" class="vmiddle legend" src="/images/common/icn_t_x300.gif"/> </td>
<td class="textOverflow" title="자동차용 엔진 및 자동차 제조업">자동차용 엔진 및 자동차 제조업</td>
<td class="textOverflow" title="자동차,자동차부품,차륜,정비 제조/도소매">자동차,자동차부품,차륜,정비 제조/도소매</td>
<td class="txc">1975-05-29</td>
<td class="txc">12월</td>
<td class="txc" title="곽재선, 황기영, 박장호(각자대표이사)">곽재선..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.kg-mobility.com" target="_blank" title="http://www.kg-mobility.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="(주)SPC삼립"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00561'); return false;" title="SPC삼립"> SPC삼립</a> </td>
<td class="textOverflow" title="기타 식품 제조업">기타 식품 제조업</td>
<td class="textOverflow" title="빵,아이스크림,과자,케익,유산균음료,인스턴트식품,병조림,면류,식용유 제조,판매">빵,아이스크림,과자,케익,유산균음료,인스턴트식품,병조림,면류,식용유 제조,판매</td>
<td class="txc">1975-05-02</td>
<td class="txc">12월</td>
<td class="txc" title="황종현, 김범수(각자 대표이사)">황종현..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.spcsamlip.co.kr" target="_blank" title="http://www.spcsamlip.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="흥국화재해상보험(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00054'); return false;" title="흥국화재"> 흥국화재</a> </td>
<td class="textOverflow" title="보험업">보험업</td>
<td class="textOverflow" title="손해보험">손해보험</td>
<td class="txc">1974-12-05</td>
<td class="txc">12월</td>
<td class="txc" title="송윤상">송윤상</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.insurance.co.kr" target="_blank" title="http://www.insurance.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="일양약품(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00757'); return false;" title="일양약품"> 일양약품</a> </td>
<td class="textOverflow" title="의약품 제조업">의약품 제조업</td>
<td class="textOverflow" title="일반의약품(원비디,영비천,아진탈,디세텔,노루모산),항암제(베타-이뮤난),전문의약품 제조,판매,수출입">일반의약품(원비디,영비천,아진탈,디세텔,노루모산),항암제(베타-이뮤난),전문의약품 제조,판매,수출입</td>
<td class="txc">1974-08-28</td>
<td class="txc">12월</td>
<td class="txc" title="김동연, 정유석">김동연..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.ilyang.co.kr" target="_blank" title="http://www.ilyang.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="(주)한진"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00232'); return false;" title="한진"> 한진</a> </td>
<td class="textOverflow" title="도로 화물 운송업">도로 화물 운송업</td>
<td class="textOverflow" title="포장화물,택배산업,항만하역,고속버스사업,운수보관">포장화물,택배산업,항만하역,고속버스사업,운수보관</td>
<td class="txc">1974-08-12</td>
<td class="txc">12월</td>
<td class="txc" title="노삼석">노삼석</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.hanjin.com" target="_blank" title="http://www.hanjin.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="한국수출포장공업(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00220'); return false;" title="한국수출포장공업"> 한국수출포장공업</a> </td>
<td class="textOverflow" title="골판지, 종이 상자 및 종이용기 제조업">골판지, 종이 상자 및 종이용기 제조업</td>
<td class="textOverflow" title="골판지상자,골판지원지 제조,판매">골판지상자,골판지원지 제조,판매</td>
<td class="txc">1974-06-28</td>
<td class="txc">12월</td>
<td class="txc" title="대표이사 회장 허용삼
대표이사 사장 허정훈(각자대표이사)">대표이..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.keppack.co.kr" target="_blank" title="http://www.keppack.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="현대자동차(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00538'); return false;" title="현대자동차"> 현대자동차</a> <img alt="V100" class="vmiddle legend" src="/images/common/icn_t_v100.gif"/> <img alt="KOSPI200" class="vmiddle legend" src="/images/common/icn_t_k200.gif"/> <img alt="KRX300" class="vmiddle legend" src="/images/common/icn_t_x300.gif"/> <img alt="KTOP30" class="vmiddle legend" src="/images/common/icn_t_ktop.gif"/> </td>
<td class="textOverflow" title="자동차용 엔진 및 자동차 제조업">자동차용 엔진 및 자동차 제조업</td>
<td class="textOverflow" title="자동차(승용차,버스,트럭,특장차),자동차부품,자동차전착도료 제조,차량정비사업">자동차(승용차,버스,트럭,특장차),자동차부품,자동차전착도료 제조,차량정비사업</td>
<td class="txc">1974-06-28</td>
<td class="txc">12월</td>
<td class="txc" title="정의선, 이동석, 무뇨스 바르셀로 호세 안토니오(각자 대표이사)">정의선..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.hyundai.com" target="_blank" title="http://www.hyundai.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)모나미"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00536'); return false;" title="모나미"> 모나미</a> </td>
<td class="textOverflow" title="생활용품 도매업">생활용품 도매업</td>
<td class="textOverflow" title="BP153(BALL POINT PEN), P-3000(PLUS PEN), 유성매직, 보드마카, 네임펜, PARKER, WARTERMAN, 색연필">BP153(BALL POINT PEN), P-3000(PLUS PEN), 유성매직, 보드마카, 네임펜, PARKER, WARTERMAN, 색연필</td>
<td class="txc">1974-06-26</td>
<td class="txc">12월</td>
<td class="txc" title="송하경">송하경</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.monami.com" target="_blank" title="http://www.monami.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="한화솔루션(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00983'); return false;" title="한화솔루션"> 한화솔루션</a> <img alt="KOSPI200" class="vmiddle legend" src="/images/common/icn_t_k200.gif"/> <img alt="KRX300" class="vmiddle legend" src="/images/common/icn_t_x300.gif"/> </td>
<td class="textOverflow" title="기초 화학물질 제조업">기초 화학물질 제조업</td>
<td class="textOverflow" title="합성수지,유화부문(LDPE,LLDPE)제품 제조,플라스틱가공품(PVC),CA,무기화학제품,부동산업">합성수지,유화부문(LDPE,LLDPE)제품 제조,플라스틱가공품(PVC),CA,무기화학제품,부동산업</td>
<td class="txc">1974-06-19</td>
<td class="txc">12월</td>
<td class="txc" title="남정운, 홍정권, 김동관">남정운..</td>
<td class="txc">
<a class="btn ico homepage" href="http://hcc.hanwha.co.kr" target="_blank" title="http://hcc.hanwha.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="아세아(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00203'); return false;" title="아세아"> 아세아</a> </td>
<td class="textOverflow" title="회사 본부 및 경영 컨설팅 서비스업">회사 본부 및 경영 컨설팅 서비스업</td>
<td class="textOverflow" title="회사본부,지주회사 및 경영컨설팅 서비스업">회사본부,지주회사 및 경영컨설팅 서비스업</td>
<td class="txc">1974-06-03</td>
<td class="txc">12월</td>
<td class="txc" title="이훈범, 오기호">이훈범..</td>
<td class="txc">
<a class="btn ico homepage" href="http://asiaholdings.co.kr" target="_blank" title="http://asiaholdings.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)카프로"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00638'); return false;" title="카프로"> 카프로</a> </td>
<td class="textOverflow" title="기초 화학물질 제조업">기초 화학물질 제조업</td>
<td class="textOverflow" title="카프로락탐,유안비료 제조">카프로락탐,유안비료 제조</td>
<td class="txc">1974-05-28</td>
<td class="txc">12월</td>
<td class="txc" title="박성명">박성명</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.hcccapro.co.kr" target="_blank" title="http://www.hcccapro.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="롯데지주(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00499'); return false;" title="롯데지주"> 롯데지주</a> <img alt="KOSPI200" class="vmiddle legend" src="/images/common/icn_t_k200.gif"/> <img alt="KRX300" class="vmiddle legend" src="/images/common/icn_t_x300.gif"/> </td>
<td class="textOverflow" title="기타 금융업">기타 금융업</td>
<td class="textOverflow" title="지주회사">지주회사</td>
<td class="txc">1974-02-16</td>
<td class="txc">12월</td>
<td class="txc" title="신동빈,이동우">신동빈..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.lotte.co.kr" target="_blank" title="http://www.lotte.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="대한방직(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00107'); return false;" title="대한방직"> 대한방직</a> </td>
<td class="textOverflow" title="직물직조 및 직물제품 제조업">직물직조 및 직물제품 제조업</td>
<td class="textOverflow" title="면사,화섬사,면직물 제조,판매,건설">면사,화섬사,면직물 제조,판매,건설</td>
<td class="txc">1973-12-28</td>
<td class="txc">12월</td>
<td class="txc" title="설 범, 김 인호">설 범..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.thtc.co.kr" target="_blank" title="http://www.thtc.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="서울식품공업(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00441'); return false;" title="서울식품공업"> 서울식품공업</a> </td>
<td class="textOverflow" title="기타 식품 제조업">기타 식품 제조업</td>
<td class="textOverflow" title="빵,스넥,마아가린,유지류,사료 제조,도매">빵,스넥,마아가린,유지류,사료 제조,도매</td>
<td class="txc">1973-12-28</td>
<td class="txc">12월</td>
<td class="txc" title="서성훈">서성훈</td>
<td class="txc">
<a class="btn ico homepage" href="http://seoul-food.co.kr" target="_blank" title="http://seoul-food.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">충청북도</td>
</tr>
<tr>
<td class="first" title="(주)아이에이치큐"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00356'); return false;" title="아이에이치큐"> 아이에이치큐</a> <img alt="관리종목" class="vmiddle legend" src="/images/common/icn_t_kwan.gif"/> </td>
<td class="textOverflow" title="영화, 비디오물, 방송프로그램 제작 및 배급업">영화, 비디오물, 방송프로그램 제작 및 배급업</td>
<td class="textOverflow" title="매니지먼트, 음반, 드라마 제작, 유료방송, 프로그램 공급, 광고대행">매니지먼트, 음반, 드라마 제작, 유료방송, 프로그램 공급, 광고대행</td>
<td class="txc">1973-12-18</td>
<td class="txc">12월</td>
<td class="txc" title="오준">오준</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.ihq.co.kr" target="_blank" title="http://www.ihq.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)LS네트웍스"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00068'); return false;" title="LS네트웍스"> LS네트웍스</a> </td>
<td class="textOverflow" title="상품 종합 도매업">상품 종합 도매업</td>
<td class="textOverflow" title="혁화,의류,등산용품 도매,제조/부동산 임대">혁화,의류,등산용품 도매,제조/부동산 임대</td>
<td class="txc">1973-11-15</td>
<td class="txc">12월</td>
<td class="txc" title="문성준">문성준</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.lsnetworks.co.kr" target="_blank" title="http://www.lsnetworks.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경상남도</td>
</tr>
<tr>
<td class="first" title="금호전기(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00121'); return false;" title="금호전기"> 금호전기</a> </td>
<td class="textOverflow" title="전구 및 조명장치 제조업">전구 및 조명장치 제조업</td>
<td class="textOverflow" title="형광등,백열전구,전구식현광등,실드빔(차량용전조) 제조,판매">형광등,백열전구,전구식현광등,실드빔(차량용전조) 제조,판매</td>
<td class="txc">1973-11-15</td>
<td class="txc">12월</td>
<td class="txc" title="이홍민">이홍민</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.khe.co.kr" target="_blank" title="http://www.khe.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="하이트진로홀딩스(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00014'); return false;" title="하이트진로홀딩스"> 하이트진로홀딩스</a> </td>
<td class="textOverflow" title="기타 금융업">기타 금융업</td>
<td class="textOverflow" title="지주회사">지주회사</td>
<td class="txc">1973-09-19</td>
<td class="txc">12월</td>
<td class="txc" title="김인규">김인규</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.hitejinroholdings.com" target="_blank" title="http://www.hitejinroholdings.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)노루홀딩스"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00032'); return false;" title="노루홀딩스"> 노루홀딩스</a> </td>
<td class="textOverflow" title="기타 금융업">기타 금융업</td>
<td class="textOverflow" title="지주사업">지주사업</td>
<td class="txc">1973-08-10</td>
<td class="txc">12월</td>
<td class="txc" title="한영재,김용기">한영재..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.norooholdings.co.kr" target="_blank" title="http://www.norooholdings.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="기아(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00027'); return false;" title="기아"> 기아</a> <img alt="V100" class="vmiddle legend" src="/images/common/icn_t_v100.gif"/> <img alt="KOSPI200" class="vmiddle legend" src="/images/common/icn_t_k200.gif"/> <img alt="KRX300" class="vmiddle legend" src="/images/common/icn_t_x300.gif"/> <img alt="KTOP30" class="vmiddle legend" src="/images/common/icn_t_ktop.gif"/> </td>
<td class="textOverflow" title="자동차용 엔진 및 자동차 제조업">자동차용 엔진 및 자동차 제조업</td>
<td class="textOverflow" title="승용차,중대형버스,트럭,민수특수차량,군수차량 제조,판매,정비">승용차,중대형버스,트럭,민수특수차량,군수차량 제조,판매,정비</td>
<td class="txc">1973-07-21</td>
<td class="txc">12월</td>
<td class="txc" title="송호성,최준영(각자 대표이사)">송호성..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.kia.co.kr" target="_blank" title="http://www.kia.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)효성"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00480'); return false;" title="효성"> 효성</a> <img alt="KRX300" class="vmiddle legend" src="/images/common/icn_t_x300.gif"/> </td>
<td class="textOverflow" title="기타 금융업">기타 금융업</td>
<td class="textOverflow" title="스판덱스,합성원사,나일론,폴리에스터,타이어코드지,PET병,수지제품,중전기제품(변압기,차단기),사무용기계,컴퓨터 제조/건축공사">스판덱스,합성원사,나일론,폴리에스터,타이어코드지,PET병,수지제품,중전기제품(변압기,차단기),사무용기계,컴퓨터 제조/건축공사</td>
<td class="txc">1973-06-30</td>
<td class="txc">12월</td>
<td class="txc" title="조현준, 황윤언">조현준..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.hyosung.com" target="_blank" title="http://www.hyosung.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="CJ(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00104'); return false;" title="CJ"> CJ</a> <img alt="KOSPI200" class="vmiddle legend" src="/images/common/icn_t_k200.gif"/> <img alt="KRX300" class="vmiddle legend" src="/images/common/icn_t_x300.gif"/> </td>
<td class="textOverflow" title="기타 금융업">기타 금융업</td>
<td class="textOverflow" title="지주회사">지주회사</td>
<td class="txc">1973-06-29</td>
<td class="txc">12월</td>
<td class="txc" title="손경식, 김홍기">손경식..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.cj.net" target="_blank" title="http://www.cj.net"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)두산"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00015'); return false;" title="두산"> 두산</a> <img alt="KOSPI200" class="vmiddle legend" src="/images/common/icn_t_k200.gif"/> <img alt="KRX300" class="vmiddle legend" src="/images/common/icn_t_x300.gif"/> </td>
<td class="textOverflow" title="기타 금융업">기타 금융업</td>
<td class="textOverflow" title="동박적층판 등 제조 및 판매, 유압기기 등 제조 및 판매, 지게차 제조 및 판매, IT 시스템 개발/운영 서비스 등, 연료전지 등">동박적층판 등 제조 및 판매, 유압기기 등 제조 및 판매, 지게차 제조 및 판매, IT 시스템 개발/운영 서비스 등, 연료전지 등</td>
<td class="txc">1973-06-29</td>
<td class="txc">12월</td>
<td class="txc" title="박정원, 김민철, 유승우">박정원..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.doosancorp.co.kr" target="_blank" title="http://www.doosancorp.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)휴스틸"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00501'); return false;" title="휴스틸"> 휴스틸</a> </td>
<td class="textOverflow" title="1차 철강 제조업">1차 철강 제조업</td>
<td class="textOverflow" title="강관(배관용,구조용,유정용) 제조,도매">강관(배관용,구조용,유정용) 제조,도매</td>
<td class="txc">1973-06-29</td>
<td class="txc">12월</td>
<td class="txc" title="박훈, 윤형원(각자 대표이사)">박훈,..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.husteel.com" target="_blank" title="http://www.husteel.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>

In [28]:
from io import StringIO

In [29]:
pd.read_html(r.text)[0]

C:\Users\Admin\AppData\Local\Temp\ipykernel_8572\1880019241.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_html(r.text)[0]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,DH오토넥스,통신 및 방송 장비 제조업,"유,무선 통신장비",1975-06-09,12월,최준용,홈페이지 보기,전북특별자치도
1,BYC,봉제의복 제조업,"메리야스,란제리 제조,도매/건축공사/부동산 임대,분양,공급",1975-06-02,12월,김 대..,홈페이지 보기,서울특별시
2,KG모빌리티,자동차용 엔진 및 자동차 제조업,"자동차,자동차부품,차륜,정비 제조/도소매",1975-05-29,12월,곽재선..,홈페이지 보기,경기도
3,SPC삼립,기타 식품 제조업,"빵,아이스크림,과자,케익,유산균음료,인스턴트식품,병조림,면류,식용유 제조,판매",1975-05-02,12월,황종현..,홈페이지 보기,경기도
4,흥국화재,보험업,손해보험,1974-12-05,12월,송윤상,홈페이지 보기,서울특별시
...,...,...,...,...,...,...,...,...
56,유한양행,의약품 제조업,"의약품(삐콤씨, 안티푸라민, 렉라자, 로수바미브, 코푸시럽 등), 생활용품(유한락스...",1962-11-01,12월,대표이..,홈페이지 보기,서울특별시
57,CJ대한통운,도로 화물 운송업,"Contract Logistics, 포워딩, 항만하역, 해운, 택배국제특송, SCM...",1956-07-02,12월,신영수..,홈페이지 보기,서울특별시
58,경방,종합 소매업,"섬유류(면사,면혼방사,면직물,면혼방직물,화섬사,화섬직물) 제조,도매,수출입",1956-03-03,12월,"김준,..",홈페이지 보기,서울특별시
59,유수홀딩스,회사 본부 및 경영 컨설팅 서비스업,지주사업,1956-03-03,12월,송영규,홈페이지 보기,서울특별시
60,한진중공업홀딩스,연료용 가스 제조 및 배관공급업,지주회사,1956-03-03,12월,조원국,홈페이지 보기,경기도

In [ ]:
pd.read_html(StringIO(r.text))[1]